//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				data about installed ETCS system
 * 			
 * 
 * <p>Java class for eETCS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eETCS">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tETCS">
 *       &lt;sequence>
 *         &lt;element name="specificTransmissionModule" type="{http://www.railml.org/schemas/2009}tSpecificTransmissionModule" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eETCS", propOrder = {
    "specificTransmissionModule"
})
public class EETCS
    extends TETCS
{

    protected TSpecificTransmissionModule specificTransmissionModule;

    /**
     * Gets the value of the specificTransmissionModule property.
     * 
     * @return
     *     possible object is
     *     {@link TSpecificTransmissionModule }
     *     
     */
    public TSpecificTransmissionModule getSpecificTransmissionModule() {
        return specificTransmissionModule;
    }

    /**
     * Sets the value of the specificTransmissionModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSpecificTransmissionModule }
     *     
     */
    public void setSpecificTransmissionModule(TSpecificTransmissionModule value) {
        this.specificTransmissionModule = value;
    }

}
