//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eInfrastructureVisualization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eInfrastructureVisualization">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tInfrastructureVisualization">
 *       &lt;sequence>
 *         &lt;element name="lineVis" type="{http://www.railml.org/schemas/2009}eLineVis" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ocpVis" type="{http://www.railml.org/schemas/2009}eOcpVis" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eInfrastructureVisualization", propOrder = {
    "lineVis",
    "ocpVis"
})
public class EInfrastructureVisualization
    extends TInfrastructureVisualization
{

    protected List<ELineVis> lineVis;
    protected List<EOcpVis> ocpVis;

    /**
     * Gets the value of the lineVis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineVis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineVis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ELineVis }
     * 
     * 
     */
    public List<ELineVis> getLineVis() {
        if (lineVis == null) {
            lineVis = new ArrayList<ELineVis>();
        }
        return this.lineVis;
    }

    /**
     * Gets the value of the ocpVis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ocpVis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOcpVis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EOcpVis }
     * 
     * 
     */
    public List<EOcpVis> getOcpVis() {
        if (ocpVis == null) {
            ocpVis = new ArrayList<EOcpVis>();
        }
        return this.ocpVis;
    }

}
