//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eOcpPropEquipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eOcpPropEquipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="summary" type="{http://www.railml.org/schemas/2009}tOcpPropEquipmentSummary"/>
 *         &lt;element name="trackRef" type="{http://www.railml.org/schemas/2009}tTrackRefInGroup" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eOcpPropEquipment", propOrder = {
    "summary",
    "trackRef"
})
public class EOcpPropEquipment {

    protected TOcpPropEquipmentSummary summary;
    protected List<TTrackRefInGroup> trackRef;

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link TOcpPropEquipmentSummary }
     *     
     */
    public TOcpPropEquipmentSummary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOcpPropEquipmentSummary }
     *     
     */
    public void setSummary(TOcpPropEquipmentSummary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the trackRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trackRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrackRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTrackRefInGroup }
     * 
     * 
     */
    public List<TTrackRefInGroup> getTrackRef() {
        if (trackRef == null) {
            trackRef = new ArrayList<TTrackRefInGroup>();
        }
        return this.trackRef;
    }

}
