//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eOcsElements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eOcsElements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="signals" type="{http://www.railml.org/schemas/2009}eSignals" minOccurs="0"/>
 *         &lt;element name="trainDetectionElements" type="{http://www.railml.org/schemas/2009}eTrainDetectionElements" minOccurs="0"/>
 *         &lt;element name="balises" type="{http://www.railml.org/schemas/2009}eBalises" minOccurs="0"/>
 *         &lt;element name="trainProtectionElements" type="{http://www.railml.org/schemas/2009}eTrainProtectionElements" minOccurs="0"/>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eOcsElements", propOrder = {
    "signals",
    "trainDetectionElements",
    "balises",
    "trainProtectionElements",
    "any"
})
public class EOcsElements {

    protected ESignals signals;
    protected ETrainDetectionElements trainDetectionElements;
    protected EBalises balises;
    protected ETrainProtectionElements trainProtectionElements;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the signals property.
     * 
     * @return
     *     possible object is
     *     {@link ESignals }
     *     
     */
    public ESignals getSignals() {
        return signals;
    }

    /**
     * Sets the value of the signals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESignals }
     *     
     */
    public void setSignals(ESignals value) {
        this.signals = value;
    }

    /**
     * Gets the value of the trainDetectionElements property.
     * 
     * @return
     *     possible object is
     *     {@link ETrainDetectionElements }
     *     
     */
    public ETrainDetectionElements getTrainDetectionElements() {
        return trainDetectionElements;
    }

    /**
     * Sets the value of the trainDetectionElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETrainDetectionElements }
     *     
     */
    public void setTrainDetectionElements(ETrainDetectionElements value) {
        this.trainDetectionElements = value;
    }

    /**
     * Gets the value of the balises property.
     * 
     * @return
     *     possible object is
     *     {@link EBalises }
     *     
     */
    public EBalises getBalises() {
        return balises;
    }

    /**
     * Sets the value of the balises property.
     * 
     * @param value
     *     allowed object is
     *     {@link EBalises }
     *     
     */
    public void setBalises(EBalises value) {
        this.balises = value;
    }

    /**
     * Gets the value of the trainProtectionElements property.
     * 
     * @return
     *     possible object is
     *     {@link ETrainProtectionElements }
     *     
     */
    public ETrainProtectionElements getTrainProtectionElements() {
        return trainProtectionElements;
    }

    /**
     * Sets the value of the trainProtectionElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETrainProtectionElements }
     *     
     */
    public void setTrainProtectionElements(ETrainProtectionElements value) {
        this.trainProtectionElements = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
