//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ePulsePattern complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ePulsePattern">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="valueTable">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.railml.org/schemas/2009}tValueTable">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ePulsePattern", propOrder = {
    "valueTable"
})
public class EPulsePattern {

    @XmlElement(required = true)
    protected EPulsePattern.ValueTable valueTable;

    /**
     * Gets the value of the valueTable property.
     * 
     * @return
     *     possible object is
     *     {@link EPulsePattern.ValueTable }
     *     
     */
    public EPulsePattern.ValueTable getValueTable() {
        return valueTable;
    }

    /**
     * Sets the value of the valueTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPulsePattern.ValueTable }
     *     
     */
    public void setValueTable(EPulsePattern.ValueTable value) {
        this.valueTable = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.railml.org/schemas/2009}tValueTable">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ValueTable
        extends TValueTable
    {


    }

}
