//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 train radio
 *             
 * 
 * <p>Java class for eTrainRadio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eTrainRadio">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tTrainRadio">
 *       &lt;sequence>
 *         &lt;element name="radioSystem" type="{http://www.railml.org/schemas/2009}tRadioSystem" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eTrainRadio", propOrder = {
    "radioSystem"
})
public class ETrainRadio
    extends TTrainRadio
{

    protected String radioSystem;

    /**
     * Gets the value of the radioSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadioSystem() {
        return radioSystem;
    }

    /**
     * Sets the value of the radioSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadioSystem(String value) {
        this.radioSystem = value;
    }

}
