//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                     container for rolling stock data of single vehicles and
 *                     train formations
 * 			
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tRollingstock">
 *       &lt;sequence>
 *         &lt;element name="vehicles" type="{http://www.railml.org/schemas/2009}eVehicles" minOccurs="0"/>
 *         &lt;element name="formations" type="{http://www.railml.org/schemas/2009}eFormations" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicles",
    "formations"
})
@XmlRootElement(name = "rollingstock")
public class Rollingstock
    extends TRollingstock
{

    protected EVehicles vehicles;
    protected EFormations formations;

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link EVehicles }
     *     
     */
    public EVehicles getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVehicles }
     *     
     */
    public void setVehicles(EVehicles value) {
        this.vehicles = value;
    }

    /**
     * Gets the value of the formations property.
     * 
     * @return
     *     possible object is
     *     {@link EFormations }
     *     
     */
    public EFormations getFormations() {
        return formations;
    }

    /**
     * Sets the value of the formations property.
     * 
     * @param value
     *     allowed object is
     *     {@link EFormations }
     *     
     */
    public void setFormations(EFormations value) {
        this.formations = value;
    }

}
