//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				technical data of eddy current brake
 * 			
 * 
 * <p>Java class for tEddyCurrentBrake complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEddyCurrentBrake">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aEddyCurrentBrake"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEddyCurrentBrake")
public class TEddyCurrentBrake {

    @XmlAttribute(name = "maxPower", required = true)
    protected BigDecimal maxPower;
    @XmlAttribute(name = "maxEffort", required = true)
    protected BigDecimal maxEffort;
    @XmlAttribute(name = "minSpeed", required = true)
    protected BigDecimal minSpeed;

    /**
     * Gets the value of the maxPower property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxPower() {
        return maxPower;
    }

    /**
     * Sets the value of the maxPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxPower(BigDecimal value) {
        this.maxPower = value;
    }

    /**
     * Gets the value of the maxEffort property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxEffort() {
        return maxEffort;
    }

    /**
     * Sets the value of the maxEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxEffort(BigDecimal value) {
        this.maxEffort = value;
    }

    /**
     * Gets the value of the minSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinSpeed() {
        return minSpeed;
    }

    /**
     * Sets the value of the minSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinSpeed(BigDecimal value) {
        this.minSpeed = value;
    }

}
