//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				container for installed capabilities with respect to
 * 				ETCS
 * 			
 * 
 * <p>Java class for tETCS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tETCS">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tElementWithIDAndName">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aMonitoringGeneric"/>
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aETCS"/>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tETCS")
@XmlSeeAlso({
    EETCS.class
})
public class TETCS
    extends TElementWithIDAndName
{

    @XmlAttribute(name = "onBoardUnitID")
    protected String onBoardUnitID;
    @XmlAttribute(name = "softwareVersion")
    protected String softwareVersion;
    @XmlAttribute(name = "srsVersion")
    protected String srsVersion;
    @XmlAttribute(name = "level_0")
    protected Boolean level0;
    @XmlAttribute(name = "level_1")
    protected Boolean level1;
    @XmlAttribute(name = "level_2")
    protected Boolean level2;
    @XmlAttribute(name = "level_3")
    protected Boolean level3;

    /**
     * Gets the value of the onBoardUnitID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnBoardUnitID() {
        return onBoardUnitID;
    }

    /**
     * Sets the value of the onBoardUnitID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnBoardUnitID(String value) {
        this.onBoardUnitID = value;
    }

    /**
     * Gets the value of the softwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareVersion(String value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the srsVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrsVersion() {
        return srsVersion;
    }

    /**
     * Sets the value of the srsVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrsVersion(String value) {
        this.srsVersion = value;
    }

    /**
     * Gets the value of the level0 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLevel0() {
        return level0;
    }

    /**
     * Sets the value of the level0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLevel0(Boolean value) {
        this.level0 = value;
    }

    /**
     * Gets the value of the level1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLevel1() {
        return level1;
    }

    /**
     * Sets the value of the level1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLevel1(Boolean value) {
        this.level1 = value;
    }

    /**
     * Gets the value of the level2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLevel2() {
        return level2;
    }

    /**
     * Sets the value of the level2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLevel2(Boolean value) {
        this.level2 = value;
    }

    /**
     * Gets the value of the level3 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLevel3() {
        return level3;
    }

    /**
     * Sets the value of the level3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLevel3(Boolean value) {
        this.level3 = value;
    }

}
