//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tTimetable">
 *       &lt;sequence>
 *         &lt;element name="timetablePeriods" type="{http://www.railml.org/schemas/2009}eTimetablePeriods" minOccurs="0"/>
 *         &lt;element name="operatingPeriods" type="{http://www.railml.org/schemas/2009}eOperatingPeriods" minOccurs="0"/>
 *         &lt;element name="categories" type="{http://www.railml.org/schemas/2009}eCategories" minOccurs="0"/>
 *         &lt;element name="trainParts" type="{http://www.railml.org/schemas/2009}eTrainParts" minOccurs="0"/>
 *         &lt;element name="trains" type="{http://www.railml.org/schemas/2009}eTrains" minOccurs="0"/>
 *         &lt;element name="trainGroups" type="{http://www.railml.org/schemas/2009}eTrainGroups" minOccurs="0"/>
 *         &lt;element name="rosterings" type="{http://www.railml.org/schemas/2009}eRosterings" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timetablePeriods",
    "operatingPeriods",
    "categories",
    "trainParts",
    "trains",
    "trainGroups",
    "rosterings"
})
@XmlRootElement(name = "timetable")
public class Timetable
    extends TTimetable
{

    protected ETimetablePeriods timetablePeriods;
    protected EOperatingPeriods operatingPeriods;
    protected ECategories categories;
    protected ETrainParts trainParts;
    protected ETrains trains;
    protected ETrainGroups trainGroups;
    protected ERosterings rosterings;

    /**
     * Gets the value of the timetablePeriods property.
     * 
     * @return
     *     possible object is
     *     {@link ETimetablePeriods }
     *     
     */
    public ETimetablePeriods getTimetablePeriods() {
        return timetablePeriods;
    }

    /**
     * Sets the value of the timetablePeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETimetablePeriods }
     *     
     */
    public void setTimetablePeriods(ETimetablePeriods value) {
        this.timetablePeriods = value;
    }

    /**
     * Gets the value of the operatingPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link EOperatingPeriods }
     *     
     */
    public EOperatingPeriods getOperatingPeriods() {
        return operatingPeriods;
    }

    /**
     * Sets the value of the operatingPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link EOperatingPeriods }
     *     
     */
    public void setOperatingPeriods(EOperatingPeriods value) {
        this.operatingPeriods = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link ECategories }
     *     
     */
    public ECategories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECategories }
     *     
     */
    public void setCategories(ECategories value) {
        this.categories = value;
    }

    /**
     * Gets the value of the trainParts property.
     * 
     * @return
     *     possible object is
     *     {@link ETrainParts }
     *     
     */
    public ETrainParts getTrainParts() {
        return trainParts;
    }

    /**
     * Sets the value of the trainParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETrainParts }
     *     
     */
    public void setTrainParts(ETrainParts value) {
        this.trainParts = value;
    }

    /**
     * Gets the value of the trains property.
     * 
     * @return
     *     possible object is
     *     {@link ETrains }
     *     
     */
    public ETrains getTrains() {
        return trains;
    }

    /**
     * Sets the value of the trains property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETrains }
     *     
     */
    public void setTrains(ETrains value) {
        this.trains = value;
    }

    /**
     * Gets the value of the trainGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ETrainGroups }
     *     
     */
    public ETrainGroups getTrainGroups() {
        return trainGroups;
    }

    /**
     * Sets the value of the trainGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETrainGroups }
     *     
     */
    public void setTrainGroups(ETrainGroups value) {
        this.trainGroups = value;
    }

    /**
     * Gets the value of the rosterings property.
     * 
     * @return
     *     possible object is
     *     {@link ERosterings }
     *     
     */
    public ERosterings getRosterings() {
        return rosterings;
    }

    /**
     * Sets the value of the rosterings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ERosterings }
     *     
     */
    public void setRosterings(ERosterings value) {
        this.rosterings = value;
    }

}
