//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tInterlockingTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tInterlockingTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="mechanical"/>
 *     &lt;enumeration value="electro-mechanical"/>
 *     &lt;enumeration value="electrical"/>
 *     &lt;enumeration value="electronical"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tInterlockingTypes")
@XmlEnum
public enum TInterlockingTypes {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("mechanical")
    MECHANICAL("mechanical"),
    @XmlEnumValue("electro-mechanical")
    ELECTRO_MECHANICAL("electro-mechanical"),
    @XmlEnumValue("electrical")
    ELECTRICAL("electrical"),
    @XmlEnumValue("electronical")
    ELECTRONICAL("electronical");
    private final String value;

    TInterlockingTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TInterlockingTypes fromValue(String v) {
        for (TInterlockingTypes c: TInterlockingTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
