//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				description of installed national train protection/monitoring systems like PZB, CIR-ELKE, TVM, LEA, ...
 * 			
 * 
 * <p>Java class for tNationalSystem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tNationalSystem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tElementWithIDAndName">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aMonitoringGeneric"/>
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aMonitoringSystem"/>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tNationalSystem")
public class TNationalSystem
    extends TElementWithIDAndName
{

    @XmlAttribute(name = "onBoardUnitID")
    protected String onBoardUnitID;
    @XmlAttribute(name = "softwareVersion")
    protected String softwareVersion;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "trainProtectionMedium", required = true)
    protected TTrainProtectionMedium trainProtectionMedium;
    @XmlAttribute(name = "trainProtectionMonitoring", required = true)
    protected TTrainProtectionMonitoring trainProtectionMonitoring;

    /**
     * Gets the value of the onBoardUnitID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnBoardUnitID() {
        return onBoardUnitID;
    }

    /**
     * Sets the value of the onBoardUnitID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnBoardUnitID(String value) {
        this.onBoardUnitID = value;
    }

    /**
     * Gets the value of the softwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareVersion(String value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the trainProtectionMedium property.
     * 
     * @return
     *     possible object is
     *     {@link TTrainProtectionMedium }
     *     
     */
    public TTrainProtectionMedium getTrainProtectionMedium() {
        return trainProtectionMedium;
    }

    /**
     * Sets the value of the trainProtectionMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrainProtectionMedium }
     *     
     */
    public void setTrainProtectionMedium(TTrainProtectionMedium value) {
        this.trainProtectionMedium = value;
    }

    /**
     * Gets the value of the trainProtectionMonitoring property.
     * 
     * @return
     *     possible object is
     *     {@link TTrainProtectionMonitoring }
     *     
     */
    public TTrainProtectionMonitoring getTrainProtectionMonitoring() {
        return trainProtectionMonitoring;
    }

    /**
     * Sets the value of the trainProtectionMonitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrainProtectionMonitoring }
     *     
     */
    public void setTrainProtectionMonitoring(TTrainProtectionMonitoring value) {
        this.trainProtectionMonitoring = value;
    }

}
