//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOcpPropService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOcpPropService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="passenger" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="service" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ship" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="bus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="tariffpoint" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="goodsLoading" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="goodsSiding" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="goodsIntermodal" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="goodsMarshalling" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOcpPropService")
public class TOcpPropService {

    @XmlAttribute(name = "passenger")
    protected Boolean passenger;
    @XmlAttribute(name = "service")
    protected Boolean service;
    @XmlAttribute(name = "ship")
    protected Boolean ship;
    @XmlAttribute(name = "bus")
    protected Boolean bus;
    @XmlAttribute(name = "tariffpoint")
    protected Boolean tariffpoint;
    @XmlAttribute(name = "goodsLoading")
    protected Boolean goodsLoading;
    @XmlAttribute(name = "goodsSiding")
    protected Boolean goodsSiding;
    @XmlAttribute(name = "goodsIntermodal")
    protected Boolean goodsIntermodal;
    @XmlAttribute(name = "goodsMarshalling")
    protected Boolean goodsMarshalling;

    /**
     * Gets the value of the passenger property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPassenger() {
        if (passenger == null) {
            return false;
        } else {
            return passenger;
        }
    }

    /**
     * Sets the value of the passenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassenger(Boolean value) {
        this.passenger = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isService() {
        if (service == null) {
            return false;
        } else {
            return service;
        }
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setService(Boolean value) {
        this.service = value;
    }

    /**
     * Gets the value of the ship property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShip() {
        if (ship == null) {
            return false;
        } else {
            return ship;
        }
    }

    /**
     * Sets the value of the ship property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShip(Boolean value) {
        this.ship = value;
    }

    /**
     * Gets the value of the bus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBus() {
        if (bus == null) {
            return false;
        } else {
            return bus;
        }
    }

    /**
     * Sets the value of the bus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBus(Boolean value) {
        this.bus = value;
    }

    /**
     * Gets the value of the tariffpoint property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTariffpoint() {
        if (tariffpoint == null) {
            return false;
        } else {
            return tariffpoint;
        }
    }

    /**
     * Sets the value of the tariffpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTariffpoint(Boolean value) {
        this.tariffpoint = value;
    }

    /**
     * Gets the value of the goodsLoading property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGoodsLoading() {
        if (goodsLoading == null) {
            return false;
        } else {
            return goodsLoading;
        }
    }

    /**
     * Sets the value of the goodsLoading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoodsLoading(Boolean value) {
        this.goodsLoading = value;
    }

    /**
     * Gets the value of the goodsSiding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGoodsSiding() {
        if (goodsSiding == null) {
            return false;
        } else {
            return goodsSiding;
        }
    }

    /**
     * Sets the value of the goodsSiding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoodsSiding(Boolean value) {
        this.goodsSiding = value;
    }

    /**
     * Gets the value of the goodsIntermodal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGoodsIntermodal() {
        if (goodsIntermodal == null) {
            return false;
        } else {
            return goodsIntermodal;
        }
    }

    /**
     * Sets the value of the goodsIntermodal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoodsIntermodal(Boolean value) {
        this.goodsIntermodal = value;
    }

    /**
     * Gets the value of the goodsMarshalling property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGoodsMarshalling() {
        if (goodsMarshalling == null) {
            return false;
        } else {
            return goodsMarshalling;
        }
    }

    /**
     * Sets the value of the goodsMarshalling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoodsMarshalling(Boolean value) {
        this.goodsMarshalling = value;
    }

}
