//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOcpUptime complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOcpUptime">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tTimeSpan">
 *       &lt;attribute name="mode" use="required" type="{http://www.railml.org/schemas/2009}tOcpManMode" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOcpUptime")
public class TOcpUptime
    extends TTimeSpan
{

    @XmlAttribute(name = "mode", required = true)
    protected TOcpManMode mode;

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link TOcpManMode }
     *     
     */
    public TOcpManMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOcpManMode }
     *     
     */
    public void setMode(TOcpManMode value) {
        this.mode = value;
    }

}
