//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				technical data about the propulsion system of a vehicle
 * 			
 * 
 * <p>Java class for tPropulsion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPropulsion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aPropulsion"/>
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aElectrificationSystem"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPropulsion")
@XmlSeeAlso({
    EPropulsion.class
})
public class TPropulsion {

    @XmlAttribute(name = "power", required = true)
    protected BigDecimal power;
    @XmlAttribute(name = "powerType", required = true)
    protected String powerType;
    @XmlAttribute(name = "transmission", required = true)
    protected String transmission;
    @XmlAttribute(name = "maxTractEffort")
    protected BigDecimal maxTractEffort;
    @XmlAttribute(name = "rotationMassFactor")
    protected BigDecimal rotationMassFactor;
    @XmlAttribute(name = "rackTraction")
    protected Boolean rackTraction;
    @XmlAttribute(name = "remoteControl")
    protected Boolean remoteControl;
    @XmlAttribute(name = "numberNotches")
    protected BigInteger numberNotches;
    @XmlAttribute(name = "wheelDiameter")
    protected BigDecimal wheelDiameter;
    @XmlAttribute(name = "maxBrakeEffort")
    protected BigDecimal maxBrakeEffort;
    @XmlAttribute(name = "maxBrakePower")
    protected BigDecimal maxBrakePower;
    @XmlAttribute(name = "totalTractEfficiency")
    protected BigDecimal totalTractEfficiency;
    @XmlAttribute(name = "totalBrakeEfficiency")
    protected BigDecimal totalBrakeEfficiency;
    @XmlAttribute(name = "tractionOffUndervoltageThreshold")
    protected BigDecimal tractionOffUndervoltageThreshold;
    @XmlAttribute(name = "zeroSpeedCurrentLimitation")
    protected BigDecimal zeroSpeedCurrentLimitation;
    @XmlAttribute(name = "maxRegenerativeVoltage")
    protected BigDecimal maxRegenerativeVoltage;
    @XmlAttribute(name = "voltage")
    protected BigDecimal voltage;
    @XmlAttribute(name = "frequency")
    protected BigDecimal frequency;

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPower(BigDecimal value) {
        this.power = value;
    }

    /**
     * Gets the value of the powerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerType() {
        return powerType;
    }

    /**
     * Sets the value of the powerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerType(String value) {
        this.powerType = value;
    }

    /**
     * Gets the value of the transmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmission() {
        return transmission;
    }

    /**
     * Sets the value of the transmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmission(String value) {
        this.transmission = value;
    }

    /**
     * Gets the value of the maxTractEffort property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxTractEffort() {
        return maxTractEffort;
    }

    /**
     * Sets the value of the maxTractEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxTractEffort(BigDecimal value) {
        this.maxTractEffort = value;
    }

    /**
     * Gets the value of the rotationMassFactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRotationMassFactor() {
        return rotationMassFactor;
    }

    /**
     * Sets the value of the rotationMassFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRotationMassFactor(BigDecimal value) {
        this.rotationMassFactor = value;
    }

    /**
     * Gets the value of the rackTraction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRackTraction() {
        return rackTraction;
    }

    /**
     * Sets the value of the rackTraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRackTraction(Boolean value) {
        this.rackTraction = value;
    }

    /**
     * Gets the value of the remoteControl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoteControl() {
        return remoteControl;
    }

    /**
     * Sets the value of the remoteControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoteControl(Boolean value) {
        this.remoteControl = value;
    }

    /**
     * Gets the value of the numberNotches property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberNotches() {
        return numberNotches;
    }

    /**
     * Sets the value of the numberNotches property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberNotches(BigInteger value) {
        this.numberNotches = value;
    }

    /**
     * Gets the value of the wheelDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWheelDiameter() {
        return wheelDiameter;
    }

    /**
     * Sets the value of the wheelDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWheelDiameter(BigDecimal value) {
        this.wheelDiameter = value;
    }

    /**
     * Gets the value of the maxBrakeEffort property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxBrakeEffort() {
        return maxBrakeEffort;
    }

    /**
     * Sets the value of the maxBrakeEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxBrakeEffort(BigDecimal value) {
        this.maxBrakeEffort = value;
    }

    /**
     * Gets the value of the maxBrakePower property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxBrakePower() {
        return maxBrakePower;
    }

    /**
     * Sets the value of the maxBrakePower property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxBrakePower(BigDecimal value) {
        this.maxBrakePower = value;
    }

    /**
     * Gets the value of the totalTractEfficiency property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTractEfficiency() {
        return totalTractEfficiency;
    }

    /**
     * Sets the value of the totalTractEfficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTractEfficiency(BigDecimal value) {
        this.totalTractEfficiency = value;
    }

    /**
     * Gets the value of the totalBrakeEfficiency property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalBrakeEfficiency() {
        return totalBrakeEfficiency;
    }

    /**
     * Sets the value of the totalBrakeEfficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalBrakeEfficiency(BigDecimal value) {
        this.totalBrakeEfficiency = value;
    }

    /**
     * Gets the value of the tractionOffUndervoltageThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTractionOffUndervoltageThreshold() {
        return tractionOffUndervoltageThreshold;
    }

    /**
     * Sets the value of the tractionOffUndervoltageThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTractionOffUndervoltageThreshold(BigDecimal value) {
        this.tractionOffUndervoltageThreshold = value;
    }

    /**
     * Gets the value of the zeroSpeedCurrentLimitation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getZeroSpeedCurrentLimitation() {
        return zeroSpeedCurrentLimitation;
    }

    /**
     * Sets the value of the zeroSpeedCurrentLimitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setZeroSpeedCurrentLimitation(BigDecimal value) {
        this.zeroSpeedCurrentLimitation = value;
    }

    /**
     * Gets the value of the maxRegenerativeVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxRegenerativeVoltage() {
        return maxRegenerativeVoltage;
    }

    /**
     * Sets the value of the maxRegenerativeVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxRegenerativeVoltage(BigDecimal value) {
        this.maxRegenerativeVoltage = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVoltage(BigDecimal value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFrequency(BigDecimal value) {
        this.frequency = value;
    }

}
