//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				mechanical train resistance vs. speed
 * 			
 * 
 * <p>Java class for tTrainResistance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTrainResistance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tCurve">
 *       &lt;attribute name="tunnelFactor" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrainResistance")
public class TTrainResistance
    extends TCurve
{

    @XmlAttribute(name = "tunnelFactor")
    protected BigDecimal tunnelFactor;

    /**
     * Gets the value of the tunnelFactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTunnelFactor() {
        return tunnelFactor;
    }

    /**
     * Sets the value of the tunnelFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTunnelFactor(BigDecimal value) {
        this.tunnelFactor = value;
    }

}
