//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTrainDetector complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTrainDetector">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tOrientedElement">
 *       &lt;attribute name="detectionObject" type="{http://www.railml.org/schemas/2009}tDetectionObject" />
 *       &lt;attribute name="medium" type="{http://www.railml.org/schemas/2009}tDetectorMedium" />
 *       &lt;attribute name="posInTrack" type="{http://www.railml.org/schemas/2009}tPosInTrack" />
 *       &lt;attribute name="directionDetection" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="axleCounting" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrainDetector")
public class TTrainDetector
    extends TOrientedElement
{

    @XmlAttribute(name = "detectionObject")
    protected TDetectionObject detectionObject;
    @XmlAttribute(name = "medium")
    protected TDetectorMedium medium;
    @XmlAttribute(name = "posInTrack")
    protected TPosInTrack posInTrack;
    @XmlAttribute(name = "directionDetection")
    protected Boolean directionDetection;
    @XmlAttribute(name = "model")
    protected String model;
    @XmlAttribute(name = "axleCounting")
    protected Boolean axleCounting;

    /**
     * Gets the value of the detectionObject property.
     * 
     * @return
     *     possible object is
     *     {@link TDetectionObject }
     *     
     */
    public TDetectionObject getDetectionObject() {
        return detectionObject;
    }

    /**
     * Sets the value of the detectionObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDetectionObject }
     *     
     */
    public void setDetectionObject(TDetectionObject value) {
        this.detectionObject = value;
    }

    /**
     * Gets the value of the medium property.
     * 
     * @return
     *     possible object is
     *     {@link TDetectorMedium }
     *     
     */
    public TDetectorMedium getMedium() {
        return medium;
    }

    /**
     * Sets the value of the medium property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDetectorMedium }
     *     
     */
    public void setMedium(TDetectorMedium value) {
        this.medium = value;
    }

    /**
     * Gets the value of the posInTrack property.
     * 
     * @return
     *     possible object is
     *     {@link TPosInTrack }
     *     
     */
    public TPosInTrack getPosInTrack() {
        return posInTrack;
    }

    /**
     * Sets the value of the posInTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPosInTrack }
     *     
     */
    public void setPosInTrack(TPosInTrack value) {
        this.posInTrack = value;
    }

    /**
     * Gets the value of the directionDetection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirectionDetection() {
        return directionDetection;
    }

    /**
     * Sets the value of the directionDetection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirectionDetection(Boolean value) {
        this.directionDetection = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the axleCounting property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAxleCounting() {
        return axleCounting;
    }

    /**
     * Sets the value of the axleCounting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAxleCounting(Boolean value) {
        this.axleCounting = value;
    }

}
