//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				technical data of main transformer
 * 			
 * 
 * <p>Java class for tTransformer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTransformer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aTransformer"/>
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aAssemblyNameNumber"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTransformer")
@XmlSeeAlso({
    ETransformer.class
})
public class TTransformer {

    @XmlAttribute(name = "ferrumResistance")
    protected BigDecimal ferrumResistance;
    @XmlAttribute(name = "additionalResistance")
    protected BigDecimal additionalResistance;
    @XmlAttribute(name = "mainInductance")
    protected BigDecimal mainInductance;
    @XmlAttribute(name = "meanEfficiency")
    protected BigDecimal meanEfficiency;
    @XmlAttribute(name = "count", required = true)
    protected BigInteger count;
    @XmlAttribute(name = "assemblyName", required = true)
    protected String assemblyName;

    /**
     * Gets the value of the ferrumResistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFerrumResistance() {
        return ferrumResistance;
    }

    /**
     * Sets the value of the ferrumResistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFerrumResistance(BigDecimal value) {
        this.ferrumResistance = value;
    }

    /**
     * Gets the value of the additionalResistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdditionalResistance() {
        return additionalResistance;
    }

    /**
     * Sets the value of the additionalResistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdditionalResistance(BigDecimal value) {
        this.additionalResistance = value;
    }

    /**
     * Gets the value of the mainInductance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMainInductance() {
        return mainInductance;
    }

    /**
     * Sets the value of the mainInductance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMainInductance(BigDecimal value) {
        this.mainInductance = value;
    }

    /**
     * Gets the value of the meanEfficiency property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMeanEfficiency() {
        return meanEfficiency;
    }

    /**
     * Sets the value of the meanEfficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMeanEfficiency(BigDecimal value) {
        this.meanEfficiency = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the assemblyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssemblyName() {
        return assemblyName;
    }

    /**
     * Sets the value of the assemblyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssemblyName(String value) {
        this.assemblyName = value;
    }

}
