package fis.railmlparser;

import javax.xml.bind.ValidationEvent;
import javax.xml.bind.ValidationEventHandler;

/**
 * Sometimes XML files generated by external applications are not strictly
 * validated and produce warnings when unmarshalled. This event handler causes
 * JAXB2 to ignore them and continue unmarshalling.
 * 
 * @author Zdravko
 */
public class CustomValidationEventHandler implements ValidationEventHandler {
    /*
     * (non-Javadoc)
     * 
     * @see javax.xml.bind.ValidationEventHandler#handleEvent(javax.xml.bind.
     * ValidationEvent)
     */
    public boolean handleEvent(ValidationEvent event) {
	return true;
    }

}
