//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 				data for train composition or vehicle formation
 * 			
 * 
 * <p>Java class for eFormation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eFormation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tFormation">
 *       &lt;sequence>
 *         &lt;element name="trainOrder" type="{http://www.railml.org/schemas/2009}eTrainOrder" minOccurs="0"/>
 *         &lt;element name="categoryRef" type="{http://www.railml.org/schemas/2009}tElementWithReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trainEngine" type="{http://www.railml.org/schemas/2009}tTrainEngine" minOccurs="0"/>
 *         &lt;element name="trainBrakes" type="{http://www.railml.org/schemas/2009}tBasicBrakeType" minOccurs="0"/>
 *         &lt;element name="trainResistance" type="{http://www.railml.org/schemas/2009}tTrainResistance" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eFormation", propOrder = {
    "trainOrder",
    "categoryRef",
    "trainEngine",
    "trainBrakes",
    "trainResistance"
})
public class EFormation
    extends TFormation
{

    protected ETrainOrder trainOrder;
    protected List<TElementWithReference> categoryRef;
    protected TTrainEngine trainEngine;
    protected TBasicBrakeType trainBrakes;
    protected TTrainResistance trainResistance;

    /**
     * Gets the value of the trainOrder property.
     * 
     * @return
     *     possible object is
     *     {@link ETrainOrder }
     *     
     */
    public ETrainOrder getTrainOrder() {
        return trainOrder;
    }

    /**
     * Sets the value of the trainOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETrainOrder }
     *     
     */
    public void setTrainOrder(ETrainOrder value) {
        this.trainOrder = value;
    }

    /**
     * Gets the value of the categoryRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TElementWithReference }
     * 
     * 
     */
    public List<TElementWithReference> getCategoryRef() {
        if (categoryRef == null) {
            categoryRef = new ArrayList<TElementWithReference>();
        }
        return this.categoryRef;
    }

    /**
     * Gets the value of the trainEngine property.
     * 
     * @return
     *     possible object is
     *     {@link TTrainEngine }
     *     
     */
    public TTrainEngine getTrainEngine() {
        return trainEngine;
    }

    /**
     * Sets the value of the trainEngine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrainEngine }
     *     
     */
    public void setTrainEngine(TTrainEngine value) {
        this.trainEngine = value;
    }

    /**
     * Gets the value of the trainBrakes property.
     * 
     * @return
     *     possible object is
     *     {@link TBasicBrakeType }
     *     
     */
    public TBasicBrakeType getTrainBrakes() {
        return trainBrakes;
    }

    /**
     * Sets the value of the trainBrakes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBasicBrakeType }
     *     
     */
    public void setTrainBrakes(TBasicBrakeType value) {
        this.trainBrakes = value;
    }

    /**
     * Gets the value of the trainResistance property.
     * 
     * @return
     *     possible object is
     *     {@link TTrainResistance }
     *     
     */
    public TTrainResistance getTrainResistance() {
        return trainResistance;
    }

    /**
     * Sets the value of the trainResistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrainResistance }
     *     
     */
    public void setTrainResistance(TTrainResistance value) {
        this.trainResistance = value;
    }

}
