//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eLine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eLine">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tLine">
 *       &lt;sequence>
 *         &lt;element name="lineDescr" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trackRef" type="{http://www.railml.org/schemas/2009}tTrackRefInGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eLine", propOrder = {
    "lineDescr",
    "trackRef"
})
public class ELine
    extends TLine
{

    protected List<String> lineDescr;
    @XmlElement(required = true)
    protected List<TTrackRefInGroup> trackRef;

    /**
     * Gets the value of the lineDescr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineDescr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineDescr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLineDescr() {
        if (lineDescr == null) {
            lineDescr = new ArrayList<String>();
        }
        return this.lineDescr;
    }

    /**
     * Gets the value of the trackRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trackRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrackRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTrackRefInGroup }
     * 
     * 
     */
    public List<TTrackRefInGroup> getTrackRef() {
        if (trackRef == null) {
            trackRef = new ArrayList<TTrackRefInGroup>();
        }
        return this.trackRef;
    }

}
