//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eMonitoring complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eMonitoring">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tMonitoring">
 *       &lt;sequence>
 *         &lt;element name="etcs" type="{http://www.railml.org/schemas/2009}eETCS" minOccurs="0"/>
 *         &lt;element name="nationalSystem" type="{http://www.railml.org/schemas/2009}tNationalSystem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trainRadio" type="{http://www.railml.org/schemas/2009}eTrainRadio" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="otherEquipment" type="{http://www.railml.org/schemas/2009}tOtherEquipment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eMonitoring", propOrder = {
    "etcs",
    "nationalSystem",
    "trainRadio",
    "otherEquipment"
})
public class EMonitoring
    extends TMonitoring
{

    protected EETCS etcs;
    protected List<TNationalSystem> nationalSystem;
    protected List<ETrainRadio> trainRadio;
    protected List<TOtherEquipment> otherEquipment;

    /**
     * Gets the value of the etcs property.
     * 
     * @return
     *     possible object is
     *     {@link EETCS }
     *     
     */
    public EETCS getEtcs() {
        return etcs;
    }

    /**
     * Sets the value of the etcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EETCS }
     *     
     */
    public void setEtcs(EETCS value) {
        this.etcs = value;
    }

    /**
     * Gets the value of the nationalSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nationalSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNationalSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TNationalSystem }
     * 
     * 
     */
    public List<TNationalSystem> getNationalSystem() {
        if (nationalSystem == null) {
            nationalSystem = new ArrayList<TNationalSystem>();
        }
        return this.nationalSystem;
    }

    /**
     * Gets the value of the trainRadio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainRadio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainRadio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ETrainRadio }
     * 
     * 
     */
    public List<ETrainRadio> getTrainRadio() {
        if (trainRadio == null) {
            trainRadio = new ArrayList<ETrainRadio>();
        }
        return this.trainRadio;
    }

    /**
     * Gets the value of the otherEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TOtherEquipment }
     * 
     * 
     */
    public List<TOtherEquipment> getOtherEquipment() {
        if (otherEquipment == null) {
            otherEquipment = new ArrayList<TOtherEquipment>();
        }
        return this.otherEquipment;
    }

}
