//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eOcpVis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eOcpVis">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tElementWithReference">
 *       &lt;sequence>
 *         &lt;element name="position" type="{http://www.railml.org/schemas/2009}tPoint"/>
 *         &lt;element name="size" type="{http://www.railml.org/schemas/2009}tSize" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eOcpVis", propOrder = {
    "position",
    "size"
})
public class EOcpVis
    extends TElementWithReference
{

    @XmlElement(required = true)
    protected TPoint position;
    protected TSize size;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link TPoint }
     *     
     */
    public TPoint getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPoint }
     *     
     */
    public void setPosition(TPoint value) {
        this.position = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link TSize }
     *     
     */
    public TSize getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSize }
     *     
     */
    public void setSize(TSize value) {
        this.size = value;
    }

}
