//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				technical data about the propulsion system of a vehicle
 * 			
 * 
 * <p>Java class for ePropulsion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ePropulsion">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tPropulsion">
 *       &lt;sequence>
 *         &lt;element name="transformer" type="{http://www.railml.org/schemas/2009}eTransformer" minOccurs="0"/>
 *         &lt;element name="fourQuadrantChopper" type="{http://www.railml.org/schemas/2009}eFourQuadrantChopper" minOccurs="0"/>
 *         &lt;element name="link" type="{http://www.railml.org/schemas/2009}tLink" minOccurs="0"/>
 *         &lt;element name="tractionInverter" type="{http://www.railml.org/schemas/2009}eTractionInverter" minOccurs="0"/>
 *         &lt;element name="tractionMotor" type="{http://www.railml.org/schemas/2009}eTractionMotor" minOccurs="0"/>
 *         &lt;element name="diesel" type="{http://www.railml.org/schemas/2009}tDieselEngine" minOccurs="0"/>
 *         &lt;element name="gear" type="{http://www.railml.org/schemas/2009}eGear" minOccurs="0"/>
 *         &lt;element name="auxiliarySupply" type="{http://www.railml.org/schemas/2009}tAuxiliarySupply" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tractiveEffort" type="{http://www.railml.org/schemas/2009}tEffortCurve" minOccurs="0"/>
 *         &lt;element name="brakeEffort" type="{http://www.railml.org/schemas/2009}tEffortCurve" minOccurs="0"/>
 *         &lt;element name="tractiveCurrent" type="{http://www.railml.org/schemas/2009}tCurrentCurve" minOccurs="0"/>
 *         &lt;element name="brakeCurrent" type="{http://www.railml.org/schemas/2009}tCurrentCurve" minOccurs="0"/>
 *         &lt;element name="tractiveCurrentLimitation" type="{http://www.railml.org/schemas/2009}tCurrentLimitation" minOccurs="0"/>
 *         &lt;element name="brakeCurrentLimitation" type="{http://www.railml.org/schemas/2009}tCurrentLimitation" minOccurs="0"/>
 *         &lt;element name="tractiveVehicleEfficiency" type="{http://www.railml.org/schemas/2009}tEfficiencyCurve" minOccurs="0"/>
 *         &lt;element name="brakeVehicleEfficiency" type="{http://www.railml.org/schemas/2009}tEfficiencyCurve" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ePropulsion", propOrder = {
    "transformer",
    "fourQuadrantChopper",
    "link",
    "tractionInverter",
    "tractionMotor",
    "diesel",
    "gear",
    "auxiliarySupply",
    "tractiveEffort",
    "brakeEffort",
    "tractiveCurrent",
    "brakeCurrent",
    "tractiveCurrentLimitation",
    "brakeCurrentLimitation",
    "tractiveVehicleEfficiency",
    "brakeVehicleEfficiency"
})
public class EPropulsion
    extends TPropulsion
{

    protected ETransformer transformer;
    protected EFourQuadrantChopper fourQuadrantChopper;
    protected TLink link;
    protected ETractionInverter tractionInverter;
    protected ETractionMotor tractionMotor;
    protected TDieselEngine diesel;
    protected EGear gear;
    protected List<TAuxiliarySupply> auxiliarySupply;
    protected TEffortCurve tractiveEffort;
    protected TEffortCurve brakeEffort;
    protected TCurrentCurve tractiveCurrent;
    protected TCurrentCurve brakeCurrent;
    protected TCurrentLimitation tractiveCurrentLimitation;
    protected TCurrentLimitation brakeCurrentLimitation;
    protected TEfficiencyCurve tractiveVehicleEfficiency;
    protected TEfficiencyCurve brakeVehicleEfficiency;

    /**
     * Gets the value of the transformer property.
     * 
     * @return
     *     possible object is
     *     {@link ETransformer }
     *     
     */
    public ETransformer getTransformer() {
        return transformer;
    }

    /**
     * Sets the value of the transformer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETransformer }
     *     
     */
    public void setTransformer(ETransformer value) {
        this.transformer = value;
    }

    /**
     * Gets the value of the fourQuadrantChopper property.
     * 
     * @return
     *     possible object is
     *     {@link EFourQuadrantChopper }
     *     
     */
    public EFourQuadrantChopper getFourQuadrantChopper() {
        return fourQuadrantChopper;
    }

    /**
     * Sets the value of the fourQuadrantChopper property.
     * 
     * @param value
     *     allowed object is
     *     {@link EFourQuadrantChopper }
     *     
     */
    public void setFourQuadrantChopper(EFourQuadrantChopper value) {
        this.fourQuadrantChopper = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link TLink }
     *     
     */
    public TLink getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLink }
     *     
     */
    public void setLink(TLink value) {
        this.link = value;
    }

    /**
     * Gets the value of the tractionInverter property.
     * 
     * @return
     *     possible object is
     *     {@link ETractionInverter }
     *     
     */
    public ETractionInverter getTractionInverter() {
        return tractionInverter;
    }

    /**
     * Sets the value of the tractionInverter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETractionInverter }
     *     
     */
    public void setTractionInverter(ETractionInverter value) {
        this.tractionInverter = value;
    }

    /**
     * Gets the value of the tractionMotor property.
     * 
     * @return
     *     possible object is
     *     {@link ETractionMotor }
     *     
     */
    public ETractionMotor getTractionMotor() {
        return tractionMotor;
    }

    /**
     * Sets the value of the tractionMotor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETractionMotor }
     *     
     */
    public void setTractionMotor(ETractionMotor value) {
        this.tractionMotor = value;
    }

    /**
     * Gets the value of the diesel property.
     * 
     * @return
     *     possible object is
     *     {@link TDieselEngine }
     *     
     */
    public TDieselEngine getDiesel() {
        return diesel;
    }

    /**
     * Sets the value of the diesel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDieselEngine }
     *     
     */
    public void setDiesel(TDieselEngine value) {
        this.diesel = value;
    }

    /**
     * Gets the value of the gear property.
     * 
     * @return
     *     possible object is
     *     {@link EGear }
     *     
     */
    public EGear getGear() {
        return gear;
    }

    /**
     * Sets the value of the gear property.
     * 
     * @param value
     *     allowed object is
     *     {@link EGear }
     *     
     */
    public void setGear(EGear value) {
        this.gear = value;
    }

    /**
     * Gets the value of the auxiliarySupply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auxiliarySupply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuxiliarySupply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAuxiliarySupply }
     * 
     * 
     */
    public List<TAuxiliarySupply> getAuxiliarySupply() {
        if (auxiliarySupply == null) {
            auxiliarySupply = new ArrayList<TAuxiliarySupply>();
        }
        return this.auxiliarySupply;
    }

    /**
     * Gets the value of the tractiveEffort property.
     * 
     * @return
     *     possible object is
     *     {@link TEffortCurve }
     *     
     */
    public TEffortCurve getTractiveEffort() {
        return tractiveEffort;
    }

    /**
     * Sets the value of the tractiveEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEffortCurve }
     *     
     */
    public void setTractiveEffort(TEffortCurve value) {
        this.tractiveEffort = value;
    }

    /**
     * Gets the value of the brakeEffort property.
     * 
     * @return
     *     possible object is
     *     {@link TEffortCurve }
     *     
     */
    public TEffortCurve getBrakeEffort() {
        return brakeEffort;
    }

    /**
     * Sets the value of the brakeEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEffortCurve }
     *     
     */
    public void setBrakeEffort(TEffortCurve value) {
        this.brakeEffort = value;
    }

    /**
     * Gets the value of the tractiveCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link TCurrentCurve }
     *     
     */
    public TCurrentCurve getTractiveCurrent() {
        return tractiveCurrent;
    }

    /**
     * Sets the value of the tractiveCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCurrentCurve }
     *     
     */
    public void setTractiveCurrent(TCurrentCurve value) {
        this.tractiveCurrent = value;
    }

    /**
     * Gets the value of the brakeCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link TCurrentCurve }
     *     
     */
    public TCurrentCurve getBrakeCurrent() {
        return brakeCurrent;
    }

    /**
     * Sets the value of the brakeCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCurrentCurve }
     *     
     */
    public void setBrakeCurrent(TCurrentCurve value) {
        this.brakeCurrent = value;
    }

    /**
     * Gets the value of the tractiveCurrentLimitation property.
     * 
     * @return
     *     possible object is
     *     {@link TCurrentLimitation }
     *     
     */
    public TCurrentLimitation getTractiveCurrentLimitation() {
        return tractiveCurrentLimitation;
    }

    /**
     * Sets the value of the tractiveCurrentLimitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCurrentLimitation }
     *     
     */
    public void setTractiveCurrentLimitation(TCurrentLimitation value) {
        this.tractiveCurrentLimitation = value;
    }

    /**
     * Gets the value of the brakeCurrentLimitation property.
     * 
     * @return
     *     possible object is
     *     {@link TCurrentLimitation }
     *     
     */
    public TCurrentLimitation getBrakeCurrentLimitation() {
        return brakeCurrentLimitation;
    }

    /**
     * Sets the value of the brakeCurrentLimitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCurrentLimitation }
     *     
     */
    public void setBrakeCurrentLimitation(TCurrentLimitation value) {
        this.brakeCurrentLimitation = value;
    }

    /**
     * Gets the value of the tractiveVehicleEfficiency property.
     * 
     * @return
     *     possible object is
     *     {@link TEfficiencyCurve }
     *     
     */
    public TEfficiencyCurve getTractiveVehicleEfficiency() {
        return tractiveVehicleEfficiency;
    }

    /**
     * Sets the value of the tractiveVehicleEfficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEfficiencyCurve }
     *     
     */
    public void setTractiveVehicleEfficiency(TEfficiencyCurve value) {
        this.tractiveVehicleEfficiency = value;
    }

    /**
     * Gets the value of the brakeVehicleEfficiency property.
     * 
     * @return
     *     possible object is
     *     {@link TEfficiencyCurve }
     *     
     */
    public TEfficiencyCurve getBrakeVehicleEfficiency() {
        return brakeVehicleEfficiency;
    }

    /**
     * Sets the value of the brakeVehicleEfficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEfficiencyCurve }
     *     
     */
    public void setBrakeVehicleEfficiency(TEfficiencyCurve value) {
        this.brakeVehicleEfficiency = value;
    }

}
