//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eRostering complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eRostering">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tRostering">
 *       &lt;sequence>
 *         &lt;element name="blockParts" type="{http://www.railml.org/schemas/2009}eBlockParts"/>
 *         &lt;element name="blocks" type="{http://www.railml.org/schemas/2009}eBlocks"/>
 *         &lt;element name="circulations" type="{http://www.railml.org/schemas/2009}eCirculations"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eRostering", propOrder = {
    "blockParts",
    "blocks",
    "circulations"
})
public class ERostering
    extends TRostering
{

    @XmlElement(required = true)
    protected EBlockParts blockParts;
    @XmlElement(required = true)
    protected EBlocks blocks;
    @XmlElement(required = true)
    protected ECirculations circulations;

    /**
     * Gets the value of the blockParts property.
     * 
     * @return
     *     possible object is
     *     {@link EBlockParts }
     *     
     */
    public EBlockParts getBlockParts() {
        return blockParts;
    }

    /**
     * Sets the value of the blockParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link EBlockParts }
     *     
     */
    public void setBlockParts(EBlockParts value) {
        this.blockParts = value;
    }

    /**
     * Gets the value of the blocks property.
     * 
     * @return
     *     possible object is
     *     {@link EBlocks }
     *     
     */
    public EBlocks getBlocks() {
        return blocks;
    }

    /**
     * Sets the value of the blocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link EBlocks }
     *     
     */
    public void setBlocks(EBlocks value) {
        this.blocks = value;
    }

    /**
     * Gets the value of the circulations property.
     * 
     * @return
     *     possible object is
     *     {@link ECirculations }
     *     
     */
    public ECirculations getCirculations() {
        return circulations;
    }

    /**
     * Sets the value of the circulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECirculations }
     *     
     */
    public void setCirculations(ECirculations value) {
        this.circulations = value;
    }

}
