//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for eSignals complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eSignals">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="signal" type="{http://www.railml.org/schemas/2009}tSignal"/>
 *         &lt;element name="signalGroups" type="{http://www.railml.org/schemas/2009}eSignalGroups"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eSignals", propOrder = {
    "signalOrSignalGroups"
})
public class ESignals {

    @XmlElements({
        @XmlElement(name = "signal", type = TSignal.class),
        @XmlElement(name = "signalGroups", type = ESignalGroups.class)
    })
    protected List<Object> signalOrSignalGroups;

    /**
     * Gets the value of the signalOrSignalGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signalOrSignalGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignalOrSignalGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSignal }
     * {@link ESignalGroups }
     * 
     * 
     */
    public List<Object> getSignalOrSignalGroups() {
        if (signalOrSignalGroups == null) {
            signalOrSignalGroups = new ArrayList<Object>();
        }
        return this.signalOrSignalGroups;
    }

}
