//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for eStatistic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eStatistic">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tStatistic">
 *       &lt;sequence>
 *         &lt;element name="mean" type="{http://www.railml.org/schemas/2009}tStatisticTimes" minOccurs="0"/>
 *         &lt;element name="median" type="{http://www.railml.org/schemas/2009}tStatisticTimes" minOccurs="0"/>
 *         &lt;element name="standardDeviation" type="{http://www.railml.org/schemas/2009}tStandardDeviationTimes" minOccurs="0"/>
 *         &lt;element name="statisticAnalyses" type="{http://www.railml.org/schemas/2009}tStatisticAnalyses" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eStatistic", propOrder = {
    "mean",
    "median",
    "standardDeviation",
    "statisticAnalyses"
})
public class EStatistic
    extends TStatistic
{

    protected TStatisticTimes mean;
    protected TStatisticTimes median;
    protected TStandardDeviationTimes standardDeviation;
    protected List<TStatisticAnalyses> statisticAnalyses;

    /**
     * Gets the value of the mean property.
     * 
     * @return
     *     possible object is
     *     {@link TStatisticTimes }
     *     
     */
    public TStatisticTimes getMean() {
        return mean;
    }

    /**
     * Sets the value of the mean property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStatisticTimes }
     *     
     */
    public void setMean(TStatisticTimes value) {
        this.mean = value;
    }

    /**
     * Gets the value of the median property.
     * 
     * @return
     *     possible object is
     *     {@link TStatisticTimes }
     *     
     */
    public TStatisticTimes getMedian() {
        return median;
    }

    /**
     * Sets the value of the median property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStatisticTimes }
     *     
     */
    public void setMedian(TStatisticTimes value) {
        this.median = value;
    }

    /**
     * Gets the value of the standardDeviation property.
     * 
     * @return
     *     possible object is
     *     {@link TStandardDeviationTimes }
     *     
     */
    public TStandardDeviationTimes getStandardDeviation() {
        return standardDeviation;
    }

    /**
     * Sets the value of the standardDeviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStandardDeviationTimes }
     *     
     */
    public void setStandardDeviation(TStandardDeviationTimes value) {
        this.standardDeviation = value;
    }

    /**
     * Gets the value of the statisticAnalyses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statisticAnalyses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatisticAnalyses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TStatisticAnalyses }
     * 
     * 
     */
    public List<TStatisticAnalyses> getStatisticAnalyses() {
        if (statisticAnalyses == null) {
            statisticAnalyses = new ArrayList<TStatisticAnalyses>();
        }
        return this.statisticAnalyses;
    }

}
