//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eTrackVis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eTrackVis">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tElementWithReference">
 *       &lt;sequence>
 *         &lt;element name="trackElementVis" type="{http://www.railml.org/schemas/2009}eTrackElementVis" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eTrackVis", propOrder = {
    "trackElementVis"
})
public class ETrackVis
    extends TElementWithReference
{

    protected List<ETrackElementVis> trackElementVis;

    /**
     * Gets the value of the trackElementVis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trackElementVis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrackElementVis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ETrackElementVis }
     * 
     * 
     */
    public List<ETrackElementVis> getTrackElementVis() {
        if (trackElementVis == null) {
            trackElementVis = new ArrayList<ETrackElementVis>();
        }
        return this.trackElementVis;
    }

}
