//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eTrackNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eTrackNode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tTrackNode">
 *       &lt;choice>
 *         &lt;element name="connection" type="{http://www.railml.org/schemas/2009}tConnectionData"/>
 *         &lt;element name="bufferStop" type="{http://www.railml.org/schemas/2009}tBufferStop"/>
 *         &lt;element name="openEnd" type="{http://www.railml.org/schemas/2009}tOpenEnd"/>
 *         &lt;element name="macroscopicNode" type="{http://www.railml.org/schemas/2009}tMacroscopicNode"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eTrackNode", propOrder = {
    "connection",
    "bufferStop",
    "openEnd",
    "macroscopicNode"
})
public class ETrackNode
    extends TTrackNode
{

    protected TConnectionData connection;
    protected TBufferStop bufferStop;
    protected TOpenEnd openEnd;
    protected TMacroscopicNode macroscopicNode;

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link TConnectionData }
     *     
     */
    public TConnectionData getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TConnectionData }
     *     
     */
    public void setConnection(TConnectionData value) {
        this.connection = value;
    }

    /**
     * Gets the value of the bufferStop property.
     * 
     * @return
     *     possible object is
     *     {@link TBufferStop }
     *     
     */
    public TBufferStop getBufferStop() {
        return bufferStop;
    }

    /**
     * Sets the value of the bufferStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBufferStop }
     *     
     */
    public void setBufferStop(TBufferStop value) {
        this.bufferStop = value;
    }

    /**
     * Gets the value of the openEnd property.
     * 
     * @return
     *     possible object is
     *     {@link TOpenEnd }
     *     
     */
    public TOpenEnd getOpenEnd() {
        return openEnd;
    }

    /**
     * Sets the value of the openEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOpenEnd }
     *     
     */
    public void setOpenEnd(TOpenEnd value) {
        this.openEnd = value;
    }

    /**
     * Gets the value of the macroscopicNode property.
     * 
     * @return
     *     possible object is
     *     {@link TMacroscopicNode }
     *     
     */
    public TMacroscopicNode getMacroscopicNode() {
        return macroscopicNode;
    }

    /**
     * Sets the value of the macroscopicNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMacroscopicNode }
     *     
     */
    public void setMacroscopicNode(TMacroscopicNode value) {
        this.macroscopicNode = value;
    }

}
