//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eVehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eVehicle">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tVehicle">
 *       &lt;sequence>
 *         &lt;element name="classification" type="{http://www.railml.org/schemas/2009}eClassification" minOccurs="0"/>
 *         &lt;element name="engine" type="{http://www.railml.org/schemas/2009}eEngine" minOccurs="0"/>
 *         &lt;element name="wagon" type="{http://www.railml.org/schemas/2009}eWagon" minOccurs="0"/>
 *         &lt;element name="vehicleBrakes" type="{http://www.railml.org/schemas/2009}eVehicleBrakes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eVehicle", propOrder = {
    "classification",
    "engine",
    "wagon",
    "vehicleBrakes"
})
public class EVehicle
    extends TVehicle
{

    protected EClassification classification;
    protected EEngine engine;
    protected EWagon wagon;
    protected EVehicleBrakes vehicleBrakes;

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link EClassification }
     *     
     */
    public EClassification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link EClassification }
     *     
     */
    public void setClassification(EClassification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link EEngine }
     *     
     */
    public EEngine getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link EEngine }
     *     
     */
    public void setEngine(EEngine value) {
        this.engine = value;
    }

    /**
     * Gets the value of the wagon property.
     * 
     * @return
     *     possible object is
     *     {@link EWagon }
     *     
     */
    public EWagon getWagon() {
        return wagon;
    }

    /**
     * Sets the value of the wagon property.
     * 
     * @param value
     *     allowed object is
     *     {@link EWagon }
     *     
     */
    public void setWagon(EWagon value) {
        this.wagon = value;
    }

    /**
     * Gets the value of the vehicleBrakes property.
     * 
     * @return
     *     possible object is
     *     {@link EVehicleBrakes }
     *     
     */
    public EVehicleBrakes getVehicleBrakes() {
        return vehicleBrakes;
    }

    /**
     * Sets the value of the vehicleBrakes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVehicleBrakes }
     *     
     */
    public void setVehicleBrakes(EVehicleBrakes value) {
        this.vehicleBrakes = value;
    }

}
