//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				data about brake systems independent from propulsion
 * 			
 * 
 * <p>Java class for eVehicleBrakes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eVehicleBrakes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vehicleBrake" type="{http://www.railml.org/schemas/2009}eVehicleBrake" maxOccurs="unbounded"/>
 *         &lt;element name="mechanicalBrakeEffort" type="{http://www.railml.org/schemas/2009}tEffortCurve" minOccurs="0"/>
 *         &lt;element name="eddyCurrentBrake" type="{http://www.railml.org/schemas/2009}tEddyCurrentBrake" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eVehicleBrakes", propOrder = {
    "vehicleBrake",
    "mechanicalBrakeEffort",
    "eddyCurrentBrake"
})
public class EVehicleBrakes {

    @XmlElement(required = true)
    protected List<EVehicleBrake> vehicleBrake;
    protected TEffortCurve mechanicalBrakeEffort;
    protected TEddyCurrentBrake eddyCurrentBrake;

    /**
     * Gets the value of the vehicleBrake property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicleBrake property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicleBrake().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EVehicleBrake }
     * 
     * 
     */
    public List<EVehicleBrake> getVehicleBrake() {
        if (vehicleBrake == null) {
            vehicleBrake = new ArrayList<EVehicleBrake>();
        }
        return this.vehicleBrake;
    }

    /**
     * Gets the value of the mechanicalBrakeEffort property.
     * 
     * @return
     *     possible object is
     *     {@link TEffortCurve }
     *     
     */
    public TEffortCurve getMechanicalBrakeEffort() {
        return mechanicalBrakeEffort;
    }

    /**
     * Sets the value of the mechanicalBrakeEffort property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEffortCurve }
     *     
     */
    public void setMechanicalBrakeEffort(TEffortCurve value) {
        this.mechanicalBrakeEffort = value;
    }

    /**
     * Gets the value of the eddyCurrentBrake property.
     * 
     * @return
     *     possible object is
     *     {@link TEddyCurrentBrake }
     *     
     */
    public TEddyCurrentBrake getEddyCurrentBrake() {
        return eddyCurrentBrake;
    }

    /**
     * Sets the value of the eddyCurrentBrake property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEddyCurrentBrake }
     *     
     */
    public void setEddyCurrentBrake(TEddyCurrentBrake value) {
        this.eddyCurrentBrake = value;
    }

}
