//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.railml.schemas._2009 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.railml.schemas._2009
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TValueTable }
     * 
     */
    public TValueTable createTValueTable() {
        return new TValueTable();
    }

    /**
     * Create an instance of {@link TValueTable.ValueLine }
     * 
     */
    public TValueTable.ValueLine createTValueTableValueLine() {
        return new TValueTable.ValueLine();
    }

    /**
     * Create an instance of {@link TCurve }
     * 
     */
    public TCurve createTCurve() {
        return new TCurve();
    }

    /**
     * Create an instance of {@link EPulsePattern }
     * 
     */
    public EPulsePattern createEPulsePattern() {
        return new EPulsePattern();
    }

    /**
     * Create an instance of {@link TBasicBrakeType }
     * 
     */
    public TBasicBrakeType createTBasicBrakeType() {
        return new TBasicBrakeType();
    }

    /**
     * Create an instance of {@link Railml }
     * 
     */
    public Railml createRailml() {
        return new Railml();
    }

    /**
     * Create an instance of {@link Infrastructure }
     * 
     */
    public Infrastructure createInfrastructure() {
        return new Infrastructure();
    }

    /**
     * Create an instance of {@link TInfrastructure }
     * 
     */
    public TInfrastructure createTInfrastructure() {
        return new TInfrastructure();
    }

    /**
     * Create an instance of {@link TGlobalElementWithMetadata }
     * 
     */
    public TGlobalElementWithMetadata createTGlobalElementWithMetadata() {
        return new TGlobalElementWithMetadata();
    }

    /**
     * Create an instance of {@link TElementWithIDAndName }
     * 
     */
    public TElementWithIDAndName createTElementWithIDAndName() {
        return new TElementWithIDAndName();
    }

    /**
     * Create an instance of {@link EInfraAttrGroup }
     * 
     */
    public EInfraAttrGroup createEInfraAttrGroup() {
        return new EInfraAttrGroup();
    }

    /**
     * Create an instance of {@link ETracks }
     * 
     */
    public ETracks createETracks() {
        return new ETracks();
    }

    /**
     * Create an instance of {@link ETrackGroups }
     * 
     */
    public ETrackGroups createETrackGroups() {
        return new ETrackGroups();
    }

    /**
     * Create an instance of {@link EOperationControlPoints }
     * 
     */
    public EOperationControlPoints createEOperationControlPoints() {
        return new EOperationControlPoints();
    }

    /**
     * Create an instance of {@link InfrastructureVisualizations }
     * 
     */
    public InfrastructureVisualizations createInfrastructureVisualizations() {
        return new InfrastructureVisualizations();
    }

    /**
     * Create an instance of {@link EInfrastructureVisualization }
     * 
     */
    public EInfrastructureVisualization createEInfrastructureVisualization() {
        return new EInfrastructureVisualization();
    }

    /**
     * Create an instance of {@link Rollingstock }
     * 
     */
    public Rollingstock createRollingstock() {
        return new Rollingstock();
    }

    /**
     * Create an instance of {@link TRollingstock }
     * 
     */
    public TRollingstock createTRollingstock() {
        return new TRollingstock();
    }

    /**
     * Create an instance of {@link EVehicles }
     * 
     */
    public EVehicles createEVehicles() {
        return new EVehicles();
    }

    /**
     * Create an instance of {@link EFormations }
     * 
     */
    public EFormations createEFormations() {
        return new EFormations();
    }

    /**
     * Create an instance of {@link Timetable }
     * 
     */
    public Timetable createTimetable() {
        return new Timetable();
    }

    /**
     * Create an instance of {@link TTimetable }
     * 
     */
    public TTimetable createTTimetable() {
        return new TTimetable();
    }

    /**
     * Create an instance of {@link ETimetablePeriods }
     * 
     */
    public ETimetablePeriods createETimetablePeriods() {
        return new ETimetablePeriods();
    }

    /**
     * Create an instance of {@link EOperatingPeriods }
     * 
     */
    public EOperatingPeriods createEOperatingPeriods() {
        return new EOperatingPeriods();
    }

    /**
     * Create an instance of {@link ECategories }
     * 
     */
    public ECategories createECategories() {
        return new ECategories();
    }

    /**
     * Create an instance of {@link ETrainParts }
     * 
     */
    public ETrainParts createETrainParts() {
        return new ETrainParts();
    }

    /**
     * Create an instance of {@link ETrains }
     * 
     */
    public ETrains createETrains() {
        return new ETrains();
    }

    /**
     * Create an instance of {@link ETrainGroups }
     * 
     */
    public ETrainGroups createETrainGroups() {
        return new ETrainGroups();
    }

    /**
     * Create an instance of {@link ERosterings }
     * 
     */
    public ERosterings createERosterings() {
        return new ERosterings();
    }

    /**
     * Create an instance of {@link TOperationMode }
     * 
     */
    public TOperationMode createTOperationMode() {
        return new TOperationMode();
    }

    /**
     * Create an instance of {@link EStatistics }
     * 
     */
    public EStatistics createEStatistics() {
        return new EStatistics();
    }

    /**
     * Create an instance of {@link EInfraAttr }
     * 
     */
    public EInfraAttr createEInfraAttr() {
        return new EInfraAttr();
    }

    /**
     * Create an instance of {@link TLink }
     * 
     */
    public TLink createTLink() {
        return new TLink();
    }

    /**
     * Create an instance of {@link ESpeedChanges }
     * 
     */
    public ESpeedChanges createESpeedChanges() {
        return new ESpeedChanges();
    }

    /**
     * Create an instance of {@link TSpeedChange }
     * 
     */
    public TSpeedChange createTSpeedChange() {
        return new TSpeedChange();
    }

    /**
     * Create an instance of {@link TBaliseRefInGroup }
     * 
     */
    public TBaliseRefInGroup createTBaliseRefInGroup() {
        return new TBaliseRefInGroup();
    }

    /**
     * Create an instance of {@link TLine }
     * 
     */
    public TLine createTLine() {
        return new TLine();
    }

    /**
     * Create an instance of {@link TEddyCurrentBrake }
     * 
     */
    public TEddyCurrentBrake createTEddyCurrentBrake() {
        return new TEddyCurrentBrake();
    }

    /**
     * Create an instance of {@link TEpsgCode }
     * 
     */
    public TEpsgCode createTEpsgCode() {
        return new TEpsgCode();
    }

    /**
     * Create an instance of {@link EBrakeUsage }
     * 
     */
    public EBrakeUsage createEBrakeUsage() {
        return new EBrakeUsage();
    }

    /**
     * Create an instance of {@link TOwnerChange }
     * 
     */
    public TOwnerChange createTOwnerChange() {
        return new TOwnerChange();
    }

    /**
     * Create an instance of {@link TBrakeUsage }
     * 
     */
    public TBrakeUsage createTBrakeUsage() {
        return new TBrakeUsage();
    }

    /**
     * Create an instance of {@link TAuxiliarySupply }
     * 
     */
    public TAuxiliarySupply createTAuxiliarySupply() {
        return new TAuxiliarySupply();
    }

    /**
     * Create an instance of {@link EBalises }
     * 
     */
    public EBalises createEBalises() {
        return new EBalises();
    }

    /**
     * Create an instance of {@link TOwner }
     * 
     */
    public TOwner createTOwner() {
        return new TOwner();
    }

    /**
     * Create an instance of {@link TSize }
     * 
     */
    public TSize createTSize() {
        return new TSize();
    }

    /**
     * Create an instance of {@link TGeoCoord }
     * 
     */
    public TGeoCoord createTGeoCoord() {
        return new TGeoCoord();
    }

    /**
     * Create an instance of {@link TService }
     * 
     */
    public TService createTService() {
        return new TService();
    }

    /**
     * Create an instance of {@link ETransformer }
     * 
     */
    public ETransformer createETransformer() {
        return new ETransformer();
    }

    /**
     * Create an instance of {@link EGear }
     * 
     */
    public EGear createEGear() {
        return new EGear();
    }

    /**
     * Create an instance of {@link TTrainGroup }
     * 
     */
    public TTrainGroup createTTrainGroup() {
        return new TTrainGroup();
    }

    /**
     * Create an instance of {@link TFormation }
     * 
     */
    public TFormation createTFormation() {
        return new TFormation();
    }

    /**
     * Create an instance of {@link EGeneralInfraAttribute }
     * 
     */
    public EGeneralInfraAttribute createEGeneralInfraAttribute() {
        return new EGeneralInfraAttribute();
    }

    /**
     * Create an instance of {@link TNationalSystem }
     * 
     */
    public TNationalSystem createTNationalSystem() {
        return new TNationalSystem();
    }

    /**
     * Create an instance of {@link EStatistic }
     * 
     */
    public EStatistic createEStatistic() {
        return new EStatistic();
    }

    /**
     * Create an instance of {@link TRadiusChange }
     * 
     */
    public TRadiusChange createTRadiusChange() {
        return new TRadiusChange();
    }

    /**
     * Create an instance of {@link ERostering }
     * 
     */
    public ERostering createERostering() {
        return new ERostering();
    }

    /**
     * Create an instance of {@link ETimetablePeriod }
     * 
     */
    public ETimetablePeriod createETimetablePeriod() {
        return new ETimetablePeriod();
    }

    /**
     * Create an instance of {@link ETractionMotor }
     * 
     */
    public ETractionMotor createETractionMotor() {
        return new ETractionMotor();
    }

    /**
     * Create an instance of {@link TOperator }
     * 
     */
    public TOperator createTOperator() {
        return new TOperator();
    }

    /**
     * Create an instance of {@link TTrainProtectionChange }
     * 
     */
    public TTrainProtectionChange createTTrainProtectionChange() {
        return new TTrainProtectionChange();
    }

    /**
     * Create an instance of {@link EBlockParts }
     * 
     */
    public EBlockParts createEBlockParts() {
        return new EBlockParts();
    }

    /**
     * Create an instance of {@link ELine }
     * 
     */
    public ELine createELine() {
        return new ELine();
    }

    /**
     * Create an instance of {@link EElectrificationChanges }
     * 
     */
    public EElectrificationChanges createEElectrificationChanges() {
        return new EElectrificationChanges();
    }

    /**
     * Create an instance of {@link TCategory }
     * 
     */
    public TCategory createTCategory() {
        return new TCategory();
    }

    /**
     * Create an instance of {@link ECrossing }
     * 
     */
    public ECrossing createECrossing() {
        return new ECrossing();
    }

    /**
     * Create an instance of {@link EFourQuadrantChopper }
     * 
     */
    public EFourQuadrantChopper createEFourQuadrantChopper() {
        return new EFourQuadrantChopper();
    }

    /**
     * Create an instance of {@link TArrivalDepartureTimes }
     * 
     */
    public TArrivalDepartureTimes createTArrivalDepartureTimes() {
        return new TArrivalDepartureTimes();
    }

    /**
     * Create an instance of {@link EBridges }
     * 
     */
    public EBridges createEBridges() {
        return new EBridges();
    }

    /**
     * Create an instance of {@link TSectionTT }
     * 
     */
    public TSectionTT createTSectionTT() {
        return new TSectionTT();
    }

    /**
     * Create an instance of {@link EOcp }
     * 
     */
    public EOcp createEOcp() {
        return new EOcp();
    }

    /**
     * Create an instance of {@link TDieselEngine }
     * 
     */
    public TDieselEngine createTDieselEngine() {
        return new TDieselEngine();
    }

    /**
     * Create an instance of {@link ESignalGroup }
     * 
     */
    public ESignalGroup createESignalGroup() {
        return new ESignalGroup();
    }

    /**
     * Create an instance of {@link TConnectionData }
     * 
     */
    public TConnectionData createTConnectionData() {
        return new TConnectionData();
    }

    /**
     * Create an instance of {@link EGaugeChanges }
     * 
     */
    public EGaugeChanges createEGaugeChanges() {
        return new EGaugeChanges();
    }

    /**
     * Create an instance of {@link TBooking }
     * 
     */
    public TBooking createTBooking() {
        return new TBooking();
    }

    /**
     * Create an instance of {@link TStopDescription }
     * 
     */
    public TStopDescription createTStopDescription() {
        return new TStopDescription();
    }

    /**
     * Create an instance of {@link EVehicle }
     * 
     */
    public EVehicle createEVehicle() {
        return new EVehicle();
    }

    /**
     * Create an instance of {@link TPowerTransmissionChange }
     * 
     */
    public TPowerTransmissionChange createTPowerTransmissionChange() {
        return new TPowerTransmissionChange();
    }

    /**
     * Create an instance of {@link TWinding }
     * 
     */
    public TWinding createTWinding() {
        return new TWinding();
    }

    /**
     * Create an instance of {@link TBridge }
     * 
     */
    public TBridge createTBridge() {
        return new TBridge();
    }

    /**
     * Create an instance of {@link TAxleWeight }
     * 
     */
    public TAxleWeight createTAxleWeight() {
        return new TAxleWeight();
    }

    /**
     * Create an instance of {@link TSwitch }
     * 
     */
    public TSwitch createTSwitch() {
        return new TSwitch();
    }

    /**
     * Create an instance of {@link TInfraAttrGroup }
     * 
     */
    public TInfraAttrGroup createTInfraAttrGroup() {
        return new TInfraAttrGroup();
    }

    /**
     * Create an instance of {@link EOwnerChanges }
     * 
     */
    public EOwnerChanges createEOwnerChanges() {
        return new EOwnerChanges();
    }

    /**
     * Create an instance of {@link TOperatingPeriodRef }
     * 
     */
    public TOperatingPeriodRef createTOperatingPeriodRef() {
        return new TOperatingPeriodRef();
    }

    /**
     * Create an instance of {@link TCommonSwitchAndCrossingData }
     * 
     */
    public TCommonSwitchAndCrossingData createTCommonSwitchAndCrossingData() {
        return new TCommonSwitchAndCrossingData();
    }

    /**
     * Create an instance of {@link EVehicleBrake }
     * 
     */
    public EVehicleBrake createEVehicleBrake() {
        return new EVehicleBrake();
    }

    /**
     * Create an instance of {@link TBorder }
     * 
     */
    public TBorder createTBorder() {
        return new TBorder();
    }

    /**
     * Create an instance of {@link TAxleWeightChange }
     * 
     */
    public TAxleWeightChange createTAxleWeightChange() {
        return new TAxleWeightChange();
    }

    /**
     * Create an instance of {@link EVehicleBrakes }
     * 
     */
    public EVehicleBrakes createEVehicleBrakes() {
        return new EVehicleBrakes();
    }

    /**
     * Create an instance of {@link TEfficiencyCurve }
     * 
     */
    public TEfficiencyCurve createTEfficiencyCurve() {
        return new TEfficiencyCurve();
    }

    /**
     * Create an instance of {@link TTrainPart }
     * 
     */
    public TTrainPart createTTrainPart() {
        return new TTrainPart();
    }

    /**
     * Create an instance of {@link TBalise }
     * 
     */
    public TBalise createTBalise() {
        return new TBalise();
    }

    /**
     * Create an instance of {@link TCurrentCurve }
     * 
     */
    public TCurrentCurve createTCurrentCurve() {
        return new TCurrentCurve();
    }

    /**
     * Create an instance of {@link EAttributes }
     * 
     */
    public EAttributes createEAttributes() {
        return new EAttributes();
    }

    /**
     * Create an instance of {@link EPassengerUsage }
     * 
     */
    public EPassengerUsage createEPassengerUsage() {
        return new EPassengerUsage();
    }

    /**
     * Create an instance of {@link TOrientedElement }
     * 
     */
    public TOrientedElement createTOrientedElement() {
        return new TOrientedElement();
    }

    /**
     * Create an instance of {@link ETrainDetectionElements }
     * 
     */
    public ETrainDetectionElements createETrainDetectionElements() {
        return new ETrainDetectionElements();
    }

    /**
     * Create an instance of {@link TGear }
     * 
     */
    public TGear createTGear() {
        return new TGear();
    }

    /**
     * Create an instance of {@link EBlockPartSequence }
     * 
     */
    public EBlockPartSequence createEBlockPartSequence() {
        return new EBlockPartSequence();
    }

    /**
     * Create an instance of {@link TBlockPartSequence }
     * 
     */
    public TBlockPartSequence createTBlockPartSequence() {
        return new TBlockPartSequence();
    }

    /**
     * Create an instance of {@link TOcpPropOther }
     * 
     */
    public TOcpPropOther createTOcpPropOther() {
        return new TOcpPropOther();
    }

    /**
     * Create an instance of {@link EGeoMappings }
     * 
     */
    public EGeoMappings createEGeoMappings() {
        return new EGeoMappings();
    }

    /**
     * Create an instance of {@link TCirculation }
     * 
     */
    public TCirculation createTCirculation() {
        return new TCirculation();
    }

    /**
     * Create an instance of {@link TOcpUptime }
     * 
     */
    public TOcpUptime createTOcpUptime() {
        return new TOcpUptime();
    }

    /**
     * Create an instance of {@link EOperatingDay }
     * 
     */
    public EOperatingDay createEOperatingDay() {
        return new EOperatingDay();
    }

    /**
     * Create an instance of {@link EFormationTT }
     * 
     */
    public EFormationTT createEFormationTT() {
        return new EFormationTT();
    }

    /**
     * Create an instance of {@link ESectionTT }
     * 
     */
    public ESectionTT createESectionTT() {
        return new ESectionTT();
    }

    /**
     * Create an instance of {@link TPropulsion }
     * 
     */
    public TPropulsion createTPropulsion() {
        return new TPropulsion();
    }

    /**
     * Create an instance of {@link TBlockPart }
     * 
     */
    public TBlockPart createTBlockPart() {
        return new TBlockPart();
    }

    /**
     * Create an instance of {@link TTransformer }
     * 
     */
    public TTransformer createTTransformer() {
        return new TTransformer();
    }

    /**
     * Create an instance of {@link TFormationTT }
     * 
     */
    public TFormationTT createTFormationTT() {
        return new TFormationTT();
    }

    /**
     * Create an instance of {@link TTrainDetector }
     * 
     */
    public TTrainDetector createTTrainDetector() {
        return new TTrainDetector();
    }

    /**
     * Create an instance of {@link ETractionInverter }
     * 
     */
    public ETractionInverter createETractionInverter() {
        return new ETractionInverter();
    }

    /**
     * Create an instance of {@link TGradientChange }
     * 
     */
    public TGradientChange createTGradientChange() {
        return new TGradientChange();
    }

    /**
     * Create an instance of {@link ETrack }
     * 
     */
    public ETrack createETrack() {
        return new ETrack();
    }

    /**
     * Create an instance of {@link TStatisticAnalyses }
     * 
     */
    public TStatisticAnalyses createTStatisticAnalyses() {
        return new TStatisticAnalyses();
    }

    /**
     * Create an instance of {@link EHolidays }
     * 
     */
    public EHolidays createEHolidays() {
        return new EHolidays();
    }

    /**
     * Create an instance of {@link TOperationModeChange }
     * 
     */
    public TOperationModeChange createTOperationModeChange() {
        return new TOperationModeChange();
    }

    /**
     * Create an instance of {@link ETrackVis }
     * 
     */
    public ETrackVis createETrackVis() {
        return new ETrackVis();
    }

    /**
     * Create an instance of {@link ESwitch }
     * 
     */
    public ESwitch createESwitch() {
        return new ESwitch();
    }

    /**
     * Create an instance of {@link TMileageChange }
     * 
     */
    public TMileageChange createTMileageChange() {
        return new TMileageChange();
    }

    /**
     * Create an instance of {@link TSwitchConnectionData }
     * 
     */
    public TSwitchConnectionData createTSwitchConnectionData() {
        return new TSwitchConnectionData();
    }

    /**
     * Create an instance of {@link TInfrastructureVisualization }
     * 
     */
    public TInfrastructureVisualization createTInfrastructureVisualization() {
        return new TInfrastructureVisualization();
    }

    /**
     * Create an instance of {@link ETrackNode }
     * 
     */
    public ETrackNode createETrackNode() {
        return new ETrackNode();
    }

    /**
     * Create an instance of {@link TTractionInverter }
     * 
     */
    public TTractionInverter createTTractionInverter() {
        return new TTractionInverter();
    }

    /**
     * Create an instance of {@link TSpecialService }
     * 
     */
    public TSpecialService createTSpecialService() {
        return new TSpecialService();
    }

    /**
     * Create an instance of {@link TOpenEnd }
     * 
     */
    public TOpenEnd createTOpenEnd() {
        return new TOpenEnd();
    }

    /**
     * Create an instance of {@link EOcpPropEquipment }
     * 
     */
    public EOcpPropEquipment createEOcpPropEquipment() {
        return new EOcpPropEquipment();
    }

    /**
     * Create an instance of {@link TTrainProtection }
     * 
     */
    public TTrainProtection createTTrainProtection() {
        return new TTrainProtection();
    }

    /**
     * Create an instance of {@link EETCS }
     * 
     */
    public EETCS createEETCS() {
        return new EETCS();
    }

    /**
     * Create an instance of {@link ETrainRadio }
     * 
     */
    public ETrainRadio createETrainRadio() {
        return new ETrainRadio();
    }

    /**
     * Create an instance of {@link TGauge }
     * 
     */
    public TGauge createTGauge() {
        return new TGauge();
    }

    /**
     * Create an instance of {@link TSignalRefInGroup }
     * 
     */
    public TSignalRefInGroup createTSignalRefInGroup() {
        return new TSignalRefInGroup();
    }

    /**
     * Create an instance of {@link TPassenger }
     * 
     */
    public TPassenger createTPassenger() {
        return new TPassenger();
    }

    /**
     * Create an instance of {@link TRunTimes }
     * 
     */
    public TRunTimes createTRunTimes() {
        return new TRunTimes();
    }

    /**
     * Create an instance of {@link TLosses }
     * 
     */
    public TLosses createTLosses() {
        return new TLosses();
    }

    /**
     * Create an instance of {@link TOcpTT }
     * 
     */
    public TOcpTT createTOcpTT() {
        return new TOcpTT();
    }

    /**
     * Create an instance of {@link TLocallyControlledArea }
     * 
     */
    public TLocallyControlledArea createTLocallyControlledArea() {
        return new TLocallyControlledArea();
    }

    /**
     * Create an instance of {@link TOcpArea }
     * 
     */
    public TOcpArea createTOcpArea() {
        return new TOcpArea();
    }

    /**
     * Create an instance of {@link TTrainProtectionElement }
     * 
     */
    public TTrainProtectionElement createTTrainProtectionElement() {
        return new TTrainProtectionElement();
    }

    /**
     * Create an instance of {@link EMileageChanges }
     * 
     */
    public EMileageChanges createEMileageChanges() {
        return new EMileageChanges();
    }

    /**
     * Create an instance of {@link EConnections }
     * 
     */
    public EConnections createEConnections() {
        return new EConnections();
    }

    /**
     * Create an instance of {@link ETrainGroup }
     * 
     */
    public ETrainGroup createETrainGroup() {
        return new ETrainGroup();
    }

    /**
     * Create an instance of {@link ELineVis }
     * 
     */
    public ELineVis createELineVis() {
        return new ELineVis();
    }

    /**
     * Create an instance of {@link TCrossSection }
     * 
     */
    public TCrossSection createTCrossSection() {
        return new TCrossSection();
    }

    /**
     * Create an instance of {@link ESpeeds }
     * 
     */
    public ESpeeds createESpeeds() {
        return new ESpeeds();
    }

    /**
     * Create an instance of {@link TOperatingPeriod }
     * 
     */
    public TOperatingPeriod createTOperatingPeriod() {
        return new TOperatingPeriod();
    }

    /**
     * Create an instance of {@link TOtherEquipment }
     * 
     */
    public TOtherEquipment createTOtherEquipment() {
        return new TOtherEquipment();
    }

    /**
     * Create an instance of {@link ETrainProtectionElements }
     * 
     */
    public ETrainProtectionElements createETrainProtectionElements() {
        return new ETrainProtectionElements();
    }

    /**
     * Create an instance of {@link EBlock }
     * 
     */
    public EBlock createEBlock() {
        return new EBlock();
    }

    /**
     * Create an instance of {@link EAxleWeightChanges }
     * 
     */
    public EAxleWeightChanges createEAxleWeightChanges() {
        return new EAxleWeightChanges();
    }

    /**
     * Create an instance of {@link EOperatingPeriodRef }
     * 
     */
    public EOperatingPeriodRef createEOperatingPeriodRef() {
        return new EOperatingPeriodRef();
    }

    /**
     * Create an instance of {@link TAttribute }
     * 
     */
    public TAttribute createTAttribute() {
        return new TAttribute();
    }

    /**
     * Create an instance of {@link EClassification }
     * 
     */
    public EClassification createEClassification() {
        return new EClassification();
    }

    /**
     * Create an instance of {@link TMonitoring }
     * 
     */
    public TMonitoring createTMonitoring() {
        return new TMonitoring();
    }

    /**
     * Create an instance of {@link ECrossSections }
     * 
     */
    public ECrossSections createECrossSections() {
        return new ECrossSections();
    }

    /**
     * Create an instance of {@link TTrainPartRef }
     * 
     */
    public TTrainPartRef createTTrainPartRef() {
        return new TTrainPartRef();
    }

    /**
     * Create an instance of {@link TOcpPropEquipmentSummary }
     * 
     */
    public TOcpPropEquipmentSummary createTOcpPropEquipmentSummary() {
        return new TOcpPropEquipmentSummary();
    }

    /**
     * Create an instance of {@link ETrackTopology }
     * 
     */
    public ETrackTopology createETrackTopology() {
        return new ETrackTopology();
    }

    /**
     * Create an instance of {@link THoliday }
     * 
     */
    public THoliday createTHoliday() {
        return new THoliday();
    }

    /**
     * Create an instance of {@link TTrainRef }
     * 
     */
    public TTrainRef createTTrainRef() {
        return new TTrainRef();
    }

    /**
     * Create an instance of {@link TStopTimes }
     * 
     */
    public TStopTimes createTStopTimes() {
        return new TStopTimes();
    }

    /**
     * Create an instance of {@link TLevelCrossing }
     * 
     */
    public TLevelCrossing createTLevelCrossing() {
        return new TLevelCrossing();
    }

    /**
     * Create an instance of {@link TPlaces }
     * 
     */
    public TPlaces createTPlaces() {
        return new TPlaces();
    }

    /**
     * Create an instance of {@link TSignalGroup }
     * 
     */
    public TSignalGroup createTSignalGroup() {
        return new TSignalGroup();
    }

    /**
     * Create an instance of {@link EOcpsTT }
     * 
     */
    public EOcpsTT createEOcpsTT() {
        return new EOcpsTT();
    }

    /**
     * Create an instance of {@link TFourQuadrantChopper }
     * 
     */
    public TFourQuadrantChopper createTFourQuadrantChopper() {
        return new TFourQuadrantChopper();
    }

    /**
     * Create an instance of {@link TVehicleRef }
     * 
     */
    public TVehicleRef createTVehicleRef() {
        return new TVehicleRef();
    }

    /**
     * Create an instance of {@link ESignals }
     * 
     */
    public ESignals createESignals() {
        return new ESignals();
    }

    /**
     * Create an instance of {@link EStopDescription }
     * 
     */
    public EStopDescription createEStopDescription() {
        return new EStopDescription();
    }

    /**
     * Create an instance of {@link TTrainEngine }
     * 
     */
    public TTrainEngine createTTrainEngine() {
        return new TTrainEngine();
    }

    /**
     * Create an instance of {@link TElementWithReference }
     * 
     */
    public TElementWithReference createTElementWithReference() {
        return new TElementWithReference();
    }

    /**
     * Create an instance of {@link TTrain }
     * 
     */
    public TTrain createTTrain() {
        return new TTrain();
    }

    /**
     * Create an instance of {@link TElectrificationChange }
     * 
     */
    public TElectrificationChange createTElectrificationChange() {
        return new TElectrificationChange();
    }

    /**
     * Create an instance of {@link EBorder }
     * 
     */
    public EBorder createEBorder() {
        return new EBorder();
    }

    /**
     * Create an instance of {@link EOcpPropOperational }
     * 
     */
    public EOcpPropOperational createEOcpPropOperational() {
        return new EOcpPropOperational();
    }

    /**
     * Create an instance of {@link TTrainRadio }
     * 
     */
    public TTrainRadio createTTrainRadio() {
        return new TTrainRadio();
    }

    /**
     * Create an instance of {@link TTimeSpan }
     * 
     */
    public TTimeSpan createTTimeSpan() {
        return new TTimeSpan();
    }

    /**
     * Create an instance of {@link TGaugeChange }
     * 
     */
    public TGaugeChange createTGaugeChange() {
        return new TGaugeChange();
    }

    /**
     * Create an instance of {@link TSpecificTransmissionModule }
     * 
     */
    public TSpecificTransmissionModule createTSpecificTransmissionModule() {
        return new TSpecificTransmissionModule();
    }

    /**
     * Create an instance of {@link EWagon }
     * 
     */
    public EWagon createEWagon() {
        return new EWagon();
    }

    /**
     * Create an instance of {@link ELevelCrossings }
     * 
     */
    public ELevelCrossings createELevelCrossings() {
        return new ELevelCrossings();
    }

    /**
     * Create an instance of {@link TSpeedInfo }
     * 
     */
    public TSpeedInfo createTSpeedInfo() {
        return new TSpeedInfo();
    }

    /**
     * Create an instance of {@link TGoods }
     * 
     */
    public TGoods createTGoods() {
        return new TGoods();
    }

    /**
     * Create an instance of {@link TGangway }
     * 
     */
    public TGangway createTGangway() {
        return new TGangway();
    }

    /**
     * Create an instance of {@link TETCS }
     * 
     */
    public TETCS createTETCS() {
        return new TETCS();
    }

    /**
     * Create an instance of {@link TCurrentLimitation }
     * 
     */
    public TCurrentLimitation createTCurrentLimitation() {
        return new TCurrentLimitation();
    }

    /**
     * Create an instance of {@link TOcpAdditionalName }
     * 
     */
    public TOcpAdditionalName createTOcpAdditionalName() {
        return new TOcpAdditionalName();
    }

    /**
     * Create an instance of {@link TTrackRefInGroup }
     * 
     */
    public TTrackRefInGroup createTTrackRefInGroup() {
        return new TTrackRefInGroup();
    }

    /**
     * Create an instance of {@link TCrossing }
     * 
     */
    public TCrossing createTCrossing() {
        return new TCrossing();
    }

    /**
     * Create an instance of {@link ECategory }
     * 
     */
    public ECategory createECategory() {
        return new ECategory();
    }

    /**
     * Create an instance of {@link EOcpVis }
     * 
     */
    public EOcpVis createEOcpVis() {
        return new EOcpVis();
    }

    /**
     * Create an instance of {@link ETrackElements }
     * 
     */
    public ETrackElements createETrackElements() {
        return new ETrackElements();
    }

    /**
     * Create an instance of {@link ETrainPart }
     * 
     */
    public ETrainPart createETrainPart() {
        return new ETrainPart();
    }

    /**
     * Create an instance of {@link EArrivalDepartureTimes }
     * 
     */
    public EArrivalDepartureTimes createEArrivalDepartureTimes() {
        return new EArrivalDepartureTimes();
    }

    /**
     * Create an instance of {@link TPlacedElement }
     * 
     */
    public TPlacedElement createTPlacedElement() {
        return new TPlacedElement();
    }

    /**
     * Create an instance of {@link ETrackElementVis }
     * 
     */
    public ETrackElementVis createETrackElementVis() {
        return new ETrackElementVis();
    }

    /**
     * Create an instance of {@link TStandardDeviationTimes }
     * 
     */
    public TStandardDeviationTimes createTStandardDeviationTimes() {
        return new TStandardDeviationTimes();
    }

    /**
     * Create an instance of {@link EGeneralInfraAttributes }
     * 
     */
    public EGeneralInfraAttributes createEGeneralInfraAttributes() {
        return new EGeneralInfraAttributes();
    }

    /**
     * Create an instance of {@link TTractionMotor }
     * 
     */
    public TTractionMotor createTTractionMotor() {
        return new TTractionMotor();
    }

    /**
     * Create an instance of {@link EEquipmentUsage }
     * 
     */
    public EEquipmentUsage createEEquipmentUsage() {
        return new EEquipmentUsage();
    }

    /**
     * Create an instance of {@link ESignalGroups }
     * 
     */
    public ESignalGroups createESignalGroups() {
        return new ESignalGroups();
    }

    /**
     * Create an instance of {@link TWagon }
     * 
     */
    public TWagon createTWagon() {
        return new TWagon();
    }

    /**
     * Create an instance of {@link TElementRefInGroup }
     * 
     */
    public TElementRefInGroup createTElementRefInGroup() {
        return new TElementRefInGroup();
    }

    /**
     * Create an instance of {@link ERadiusChanges }
     * 
     */
    public ERadiusChanges createERadiusChanges() {
        return new ERadiusChanges();
    }

    /**
     * Create an instance of {@link TTrainPartSequence }
     * 
     */
    public TTrainPartSequence createTTrainPartSequence() {
        return new TTrainPartSequence();
    }

    /**
     * Create an instance of {@link EReservationInfo }
     * 
     */
    public EReservationInfo createEReservationInfo() {
        return new EReservationInfo();
    }

    /**
     * Create an instance of {@link ETrain }
     * 
     */
    public ETrain createETrain() {
        return new ETrain();
    }

    /**
     * Create an instance of {@link TStatistic }
     * 
     */
    public TStatistic createTStatistic() {
        return new TStatistic();
    }

    /**
     * Create an instance of {@link ELocallyControlledArea }
     * 
     */
    public ELocallyControlledArea createELocallyControlledArea() {
        return new ELocallyControlledArea();
    }

    /**
     * Create an instance of {@link TEquipment }
     * 
     */
    public TEquipment createTEquipment() {
        return new TEquipment();
    }

    /**
     * Create an instance of {@link TRostering }
     * 
     */
    public TRostering createTRostering() {
        return new TRostering();
    }

    /**
     * Create an instance of {@link TTimetablePeriod }
     * 
     */
    public TTimetablePeriod createTTimetablePeriod() {
        return new TTimetablePeriod();
    }

    /**
     * Create an instance of {@link TTrackCircuitBorder }
     * 
     */
    public TTrackCircuitBorder createTTrackCircuitBorder() {
        return new TTrackCircuitBorder();
    }

    /**
     * Create an instance of {@link EFormation }
     * 
     */
    public EFormation createEFormation() {
        return new EFormation();
    }

    /**
     * Create an instance of {@link ETunnels }
     * 
     */
    public ETunnels createETunnels() {
        return new ETunnels();
    }

    /**
     * Create an instance of {@link TManufacturer }
     * 
     */
    public TManufacturer createTManufacturer() {
        return new TManufacturer();
    }

    /**
     * Create an instance of {@link EPassenger }
     * 
     */
    public EPassenger createEPassenger() {
        return new EPassenger();
    }

    /**
     * Create an instance of {@link ETrainProtectionChanges }
     * 
     */
    public ETrainProtectionChanges createETrainProtectionChanges() {
        return new ETrainProtectionChanges();
    }

    /**
     * Create an instance of {@link TTunnel }
     * 
     */
    public TTunnel createTTunnel() {
        return new TTunnel();
    }

    /**
     * Create an instance of {@link TOcpPropService }
     * 
     */
    public TOcpPropService createTOcpPropService() {
        return new TOcpPropService();
    }

    /**
     * Create an instance of {@link EOcsElements }
     * 
     */
    public EOcsElements createEOcsElements() {
        return new EOcsElements();
    }

    /**
     * Create an instance of {@link TConnectionTT }
     * 
     */
    public TConnectionTT createTConnectionTT() {
        return new TConnectionTT();
    }

    /**
     * Create an instance of {@link EConnectionsTT }
     * 
     */
    public EConnectionsTT createEConnectionsTT() {
        return new EConnectionsTT();
    }

    /**
     * Create an instance of {@link ETrainOrder }
     * 
     */
    public ETrainOrder createETrainOrder() {
        return new ETrainOrder();
    }

    /**
     * Create an instance of {@link TVehicle }
     * 
     */
    public TVehicle createTVehicle() {
        return new TVehicle();
    }

    /**
     * Create an instance of {@link TBlock }
     * 
     */
    public TBlock createTBlock() {
        return new TBlock();
    }

    /**
     * Create an instance of {@link TMacroscopicNode }
     * 
     */
    public TMacroscopicNode createTMacroscopicNode() {
        return new TMacroscopicNode();
    }

    /**
     * Create an instance of {@link ETrainPartSequence }
     * 
     */
    public ETrainPartSequence createETrainPartSequence() {
        return new ETrainPartSequence();
    }

    /**
     * Create an instance of {@link TTrainResistance }
     * 
     */
    public TTrainResistance createTTrainResistance() {
        return new TTrainResistance();
    }

    /**
     * Create an instance of {@link TOperationControlPoint }
     * 
     */
    public TOperationControlPoint createTOperationControlPoint() {
        return new TOperationControlPoint();
    }

    /**
     * Create an instance of {@link EBlocks }
     * 
     */
    public EBlocks createEBlocks() {
        return new EBlocks();
    }

    /**
     * Create an instance of {@link TSignal }
     * 
     */
    public TSignal createTSignal() {
        return new TSignal();
    }

    /**
     * Create an instance of {@link EBaliseGroup }
     * 
     */
    public EBaliseGroup createEBaliseGroup() {
        return new EBaliseGroup();
    }

    /**
     * Create an instance of {@link TStatisticTimes }
     * 
     */
    public TStatisticTimes createTStatisticTimes() {
        return new TStatisticTimes();
    }

    /**
     * Create an instance of {@link EEngine }
     * 
     */
    public EEngine createEEngine() {
        return new EEngine();
    }

    /**
     * Create an instance of {@link EOcpTT }
     * 
     */
    public EOcpTT createEOcpTT() {
        return new EOcpTT();
    }

    /**
     * Create an instance of {@link TElectrification }
     * 
     */
    public TElectrification createTElectrification() {
        return new TElectrification();
    }

    /**
     * Create an instance of {@link ECirculations }
     * 
     */
    public ECirculations createECirculations() {
        return new ECirculations();
    }

    /**
     * Create an instance of {@link TOperatingDayDeviance }
     * 
     */
    public TOperatingDayDeviance createTOperatingDayDeviance() {
        return new TOperatingDayDeviance();
    }

    /**
     * Create an instance of {@link EPowerTransmissionChanges }
     * 
     */
    public EPowerTransmissionChanges createEPowerTransmissionChanges() {
        return new EPowerTransmissionChanges();
    }

    /**
     * Create an instance of {@link EGradientChanges }
     * 
     */
    public EGradientChanges createEGradientChanges() {
        return new EGradientChanges();
    }

    /**
     * Create an instance of {@link TEffortCurve }
     * 
     */
    public TEffortCurve createTEffortCurve() {
        return new TEffortCurve();
    }

    /**
     * Create an instance of {@link EPropulsion }
     * 
     */
    public EPropulsion createEPropulsion() {
        return new EPropulsion();
    }

    /**
     * Create an instance of {@link TBufferStop }
     * 
     */
    public TBufferStop createTBufferStop() {
        return new TBufferStop();
    }

    /**
     * Create an instance of {@link TOperatingDay }
     * 
     */
    public TOperatingDay createTOperatingDay() {
        return new TOperatingDay();
    }

    /**
     * Create an instance of {@link TTrackNode }
     * 
     */
    public TTrackNode createTTrackNode() {
        return new TTrackNode();
    }

    /**
     * Create an instance of {@link TBlockPartRef }
     * 
     */
    public TBlockPartRef createTBlockPartRef() {
        return new TBlockPartRef();
    }

    /**
     * Create an instance of {@link TTrack }
     * 
     */
    public TTrack createTTrack() {
        return new TTrack();
    }

    /**
     * Create an instance of {@link TPoint }
     * 
     */
    public TPoint createTPoint() {
        return new TPoint();
    }

    /**
     * Create an instance of {@link EOperationModeChanges }
     * 
     */
    public EOperationModeChanges createEOperationModeChanges() {
        return new EOperationModeChanges();
    }

    /**
     * Create an instance of {@link EOcpPropOther }
     * 
     */
    public EOcpPropOther createEOcpPropOther() {
        return new EOcpPropOther();
    }

    /**
     * Create an instance of {@link TOcpPropOperational }
     * 
     */
    public TOcpPropOperational createTOcpPropOperational() {
        return new TOcpPropOperational();
    }

    /**
     * Create an instance of {@link TPowerTransmission }
     * 
     */
    public TPowerTransmission createTPowerTransmission() {
        return new TPowerTransmission();
    }

    /**
     * Create an instance of {@link EMonitoring }
     * 
     */
    public EMonitoring createEMonitoring() {
        return new EMonitoring();
    }

    /**
     * Create an instance of {@link EOperatingPeriod }
     * 
     */
    public EOperatingPeriod createEOperatingPeriod() {
        return new EOperatingPeriod();
    }

    /**
     * Create an instance of {@link TValueTable.ColumnHeader }
     * 
     */
    public TValueTable.ColumnHeader createTValueTableColumnHeader() {
        return new TValueTable.ColumnHeader();
    }

    /**
     * Create an instance of {@link TValueTable.ValueLine.Values }
     * 
     */
    public TValueTable.ValueLine.Values createTValueTableValueLineValues() {
        return new TValueTable.ValueLine.Values();
    }

    /**
     * Create an instance of {@link TCurve.ValueTable }
     * 
     */
    public TCurve.ValueTable createTCurveValueTable() {
        return new TCurve.ValueTable();
    }

    /**
     * Create an instance of {@link EPulsePattern.ValueTable }
     * 
     */
    public EPulsePattern.ValueTable createEPulsePatternValueTable() {
        return new EPulsePattern.ValueTable();
    }

    /**
     * Create an instance of {@link TBasicBrakeType.AuxiliaryBrakes }
     * 
     */
    public TBasicBrakeType.AuxiliaryBrakes createTBasicBrakeTypeAuxiliaryBrakes() {
        return new TBasicBrakeType.AuxiliaryBrakes();
    }

}
