//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tBalise complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tBalise">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tOrientedElement">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aBalise"/>
 *       &lt;attribute name="ndx" type="{http://www.railml.org/schemas/2009}tPIG" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tBalise")
public class TBalise
    extends TOrientedElement
{

    @XmlAttribute(name = "ndx")
    protected Integer ndx;
    @XmlAttribute(name = "countryID")
    protected Integer countryID;
    @XmlAttribute(name = "groupID")
    protected Integer groupID;
    @XmlAttribute(name = "linkingAccuracy")
    protected Integer linkingAccuracy;
    @XmlAttribute(name = "linkReactionAscending")
    protected TBaliseLinkReaction linkReactionAscending;
    @XmlAttribute(name = "linkReactionDescending")
    protected TBaliseLinkReaction linkReactionDescending;
    @XmlAttribute(name = "staticTelegram")
    protected String staticTelegram;

    /**
     * Gets the value of the ndx property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNdx() {
        return ndx;
    }

    /**
     * Sets the value of the ndx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNdx(Integer value) {
        this.ndx = value;
    }

    /**
     * Gets the value of the countryID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCountryID() {
        return countryID;
    }

    /**
     * Sets the value of the countryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCountryID(Integer value) {
        this.countryID = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupID(Integer value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the linkingAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLinkingAccuracy() {
        return linkingAccuracy;
    }

    /**
     * Sets the value of the linkingAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLinkingAccuracy(Integer value) {
        this.linkingAccuracy = value;
    }

    /**
     * Gets the value of the linkReactionAscending property.
     * 
     * @return
     *     possible object is
     *     {@link TBaliseLinkReaction }
     *     
     */
    public TBaliseLinkReaction getLinkReactionAscending() {
        return linkReactionAscending;
    }

    /**
     * Sets the value of the linkReactionAscending property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBaliseLinkReaction }
     *     
     */
    public void setLinkReactionAscending(TBaliseLinkReaction value) {
        this.linkReactionAscending = value;
    }

    /**
     * Gets the value of the linkReactionDescending property.
     * 
     * @return
     *     possible object is
     *     {@link TBaliseLinkReaction }
     *     
     */
    public TBaliseLinkReaction getLinkReactionDescending() {
        return linkReactionDescending;
    }

    /**
     * Sets the value of the linkReactionDescending property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBaliseLinkReaction }
     *     
     */
    public void setLinkReactionDescending(TBaliseLinkReaction value) {
        this.linkReactionDescending = value;
    }

    /**
     * Gets the value of the staticTelegram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaticTelegram() {
        return staticTelegram;
    }

    /**
     * Sets the value of the staticTelegram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaticTelegram(String value) {
        this.staticTelegram = value;
    }

}
