//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for tCommonSwitchAndCrossingData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCommonSwitchAndCrossingData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tPlacedElement">
 *       &lt;attribute name="trackContinueCourse" type="{http://www.railml.org/schemas/2009}tCourse" />
 *       &lt;attribute name="trackContinueRadius" type="{http://www.railml.org/schemas/2009}tRadiusM" />
 *       &lt;attribute name="normalPosition" type="{http://www.railml.org/schemas/2009}tCourse" />
 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length" type="{http://www.railml.org/schemas/2009}tLengthM" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCommonSwitchAndCrossingData")
@XmlSeeAlso({
    TSwitch.class,
    TCrossing.class
})
public class TCommonSwitchAndCrossingData
    extends TPlacedElement
{

    @XmlAttribute(name = "trackContinueCourse")
    protected TCourse trackContinueCourse;
    @XmlAttribute(name = "trackContinueRadius")
    protected BigDecimal trackContinueRadius;
    @XmlAttribute(name = "normalPosition")
    protected TCourse normalPosition;
    @XmlAttribute(name = "model")
    protected String model;
    @XmlAttribute(name = "length")
    protected BigDecimal length;

    /**
     * Gets the value of the trackContinueCourse property.
     * 
     * @return
     *     possible object is
     *     {@link TCourse }
     *     
     */
    public TCourse getTrackContinueCourse() {
        return trackContinueCourse;
    }

    /**
     * Sets the value of the trackContinueCourse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCourse }
     *     
     */
    public void setTrackContinueCourse(TCourse value) {
        this.trackContinueCourse = value;
    }

    /**
     * Gets the value of the trackContinueRadius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrackContinueRadius() {
        return trackContinueRadius;
    }

    /**
     * Sets the value of the trackContinueRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrackContinueRadius(BigDecimal value) {
        this.trackContinueRadius = value;
    }

    /**
     * Gets the value of the normalPosition property.
     * 
     * @return
     *     possible object is
     *     {@link TCourse }
     *     
     */
    public TCourse getNormalPosition() {
        return normalPosition;
    }

    /**
     * Sets the value of the normalPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCourse }
     *     
     */
    public void setNormalPosition(TCourse value) {
        this.normalPosition = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLength(BigDecimal value) {
        this.length = value;
    }

}
