//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for tConnectionTT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tConnectionTT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aConnectionTT"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tConnectionTT")
public class TConnectionTT {

    @XmlAttribute(name = "trainRef", required = true)
    @XmlIDREF
    protected Object trainRef;
    @XmlAttribute(name = "minConnTime")
    protected Duration minConnTime;
    @XmlAttribute(name = "maxConnTime")
    protected Duration maxConnTime;
    @XmlAttribute(name = "connOperation")
    protected String connOperation;

    /**
     * Gets the value of the trainRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTrainRef() {
        return trainRef;
    }

    /**
     * Sets the value of the trainRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTrainRef(Object value) {
        this.trainRef = value;
    }

    /**
     * Gets the value of the minConnTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMinConnTime() {
        return minConnTime;
    }

    /**
     * Sets the value of the minConnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMinConnTime(Duration value) {
        this.minConnTime = value;
    }

    /**
     * Gets the value of the maxConnTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMaxConnTime() {
        return maxConnTime;
    }

    /**
     * Sets the value of the maxConnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMaxConnTime(Duration value) {
        this.maxConnTime = value;
    }

    /**
     * Gets the value of the connOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnOperation() {
        return connOperation;
    }

    /**
     * Sets the value of the connOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnOperation(String value) {
        this.connOperation = value;
    }

}
