//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tCrossSection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCrossSection">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tOrientedElement">
 *       &lt;attribute name="type" type="{http://www.railml.org/schemas/2009}tCrossSectionBlockType" />
 *       &lt;attribute name="ocpRef" use="required" type="{http://www.railml.org/schemas/2009}tGenericRef" />
 *       &lt;attribute name="ocpTrackID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCrossSection")
public class TCrossSection
    extends TOrientedElement
{

    @XmlAttribute(name = "type")
    protected TCrossSectionBlockType type;
    @XmlAttribute(name = "ocpRef", required = true)
    @XmlIDREF
    protected Object ocpRef;
    @XmlAttribute(name = "ocpTrackID")
    @XmlSchemaType(name = "unsignedByte")
    protected Short ocpTrackID;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TCrossSectionBlockType }
     *     
     */
    public TCrossSectionBlockType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCrossSectionBlockType }
     *     
     */
    public void setType(TCrossSectionBlockType value) {
        this.type = value;
    }

    /**
     * Gets the value of the ocpRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOcpRef() {
        return ocpRef;
    }

    /**
     * Sets the value of the ocpRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOcpRef(Object value) {
        this.ocpRef = value;
    }

    /**
     * Gets the value of the ocpTrackID property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getOcpTrackID() {
        return ocpTrackID;
    }

    /**
     * Sets the value of the ocpTrackID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setOcpTrackID(Short value) {
        this.ocpTrackID = value;
    }

}
