//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3._1998.math.mathml.MathType;


/**
 * 
 * 				generic curve of function y=f(x,z)
 * 			
 * 
 * <p>Java class for tCurve complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCurve">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/1998/Math/MathML}math" minOccurs="0"/>
 *         &lt;element name="valueTable" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.railml.org/schemas/2009}tValueTable">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCurve", propOrder = {
    "math",
    "valueTable"
})
@XmlSeeAlso({
    TEfficiencyCurve.class,
    TCurrentCurve.class,
    TLosses.class,
    TCurrentLimitation.class,
    TTrainResistance.class,
    TEffortCurve.class
})
public class TCurve {

    @XmlElement(namespace = "http://www.w3.org/1998/Math/MathML")
    protected MathType math;
    protected TCurve.ValueTable valueTable;

    /**
     * 
     * 						function definition vs. arbitrary variable in
     * 						MathML format
     * 					
     * 
     * @return
     *     possible object is
     *     {@link MathType }
     *     
     */
    public MathType getMath() {
        return math;
    }

    /**
     * Sets the value of the math property.
     * 
     * @param value
     *     allowed object is
     *     {@link MathType }
     *     
     */
    public void setMath(MathType value) {
        this.math = value;
    }

    /**
     * Gets the value of the valueTable property.
     * 
     * @return
     *     possible object is
     *     {@link TCurve.ValueTable }
     *     
     */
    public TCurve.ValueTable getValueTable() {
        return valueTable;
    }

    /**
     * Sets the value of the valueTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCurve.ValueTable }
     *     
     */
    public void setValueTable(TCurve.ValueTable value) {
        this.valueTable = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.railml.org/schemas/2009}tValueTable">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ValueTable
        extends TValueTable
    {


    }

}
