//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tGradientChange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGradientChange">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tOrientedElement">
 *       &lt;attribute name="slope" use="required" type="{http://www.railml.org/schemas/2009}tGradientPromille" />
 *       &lt;attribute name="transitionLenght" type="{http://www.railml.org/schemas/2009}tLengthM" />
 *       &lt;attribute name="transitionRadius" type="{http://www.railml.org/schemas/2009}tRadiusM" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGradientChange")
public class TGradientChange
    extends TOrientedElement
{

    @XmlAttribute(name = "slope", required = true)
    protected BigDecimal slope;
    @XmlAttribute(name = "transitionLenght")
    protected BigDecimal transitionLenght;
    @XmlAttribute(name = "transitionRadius")
    protected BigDecimal transitionRadius;

    /**
     * Gets the value of the slope property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSlope() {
        return slope;
    }

    /**
     * Sets the value of the slope property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSlope(BigDecimal value) {
        this.slope = value;
    }

    /**
     * Gets the value of the transitionLenght property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTransitionLenght() {
        return transitionLenght;
    }

    /**
     * Sets the value of the transitionLenght property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTransitionLenght(BigDecimal value) {
        this.transitionLenght = value;
    }

    /**
     * Gets the value of the transitionRadius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTransitionRadius() {
        return transitionRadius;
    }

    /**
     * Sets the value of the transitionRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTransitionRadius(BigDecimal value) {
        this.transitionRadius = value;
    }

}
