//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tInfrastructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tInfrastructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tGlobalElementWithMetadata">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aInfrastructure"/>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInfrastructure")
@XmlSeeAlso({
    Infrastructure.class
})
public class TInfrastructure
    extends TGlobalElementWithMetadata
{

    @XmlAttribute(name = "timetableRef")
    @XmlIDREF
    protected Object timetableRef;
    @XmlAttribute(name = "rollingstockRef")
    @XmlIDREF
    protected Object rollingstockRef;

    /**
     * Gets the value of the timetableRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTimetableRef() {
        return timetableRef;
    }

    /**
     * Sets the value of the timetableRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTimetableRef(Object value) {
        this.timetableRef = value;
    }

    /**
     * Gets the value of the rollingstockRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRollingstockRef() {
        return rollingstockRef;
    }

    /**
     * Sets the value of the rollingstockRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRollingstockRef(Object value) {
        this.rollingstockRef = value;
    }

}
