//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tMacroscopicNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMacroscopicNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ocpRef" use="required" type="{http://www.railml.org/schemas/2009}tGenericRef" />
 *       &lt;attribute name="flowDirection" type="{http://www.railml.org/schemas/2009}tFlowDirection" default="both" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMacroscopicNode")
public class TMacroscopicNode {

    @XmlAttribute(name = "ocpRef", required = true)
    @XmlIDREF
    protected Object ocpRef;
    @XmlAttribute(name = "flowDirection")
    protected TFlowDirection flowDirection;

    /**
     * Gets the value of the ocpRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOcpRef() {
        return ocpRef;
    }

    /**
     * Sets the value of the ocpRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOcpRef(Object value) {
        this.ocpRef = value;
    }

    /**
     * Gets the value of the flowDirection property.
     * 
     * @return
     *     possible object is
     *     {@link TFlowDirection }
     *     
     */
    public TFlowDirection getFlowDirection() {
        if (flowDirection == null) {
            return TFlowDirection.BOTH;
        } else {
            return flowDirection;
        }
    }

    /**
     * Sets the value of the flowDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFlowDirection }
     *     
     */
    public void setFlowDirection(TFlowDirection value) {
        this.flowDirection = value;
    }

}
