//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOcpOperationalType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tOcpOperationalType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="station"/>
 *     &lt;enumeration value="depot"/>
 *     &lt;enumeration value="stoppingPoint"/>
 *     &lt;enumeration value="crossover"/>
 *     &lt;enumeration value="junction"/>
 *     &lt;enumeration value="blockPost"/>
 *     &lt;enumeration value="blockSignal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tOcpOperationalType")
@XmlEnum
public enum TOcpOperationalType {

    @XmlEnumValue("station")
    STATION("station"),
    @XmlEnumValue("depot")
    DEPOT("depot"),
    @XmlEnumValue("stoppingPoint")
    STOPPING_POINT("stoppingPoint"),
    @XmlEnumValue("crossover")
    CROSSOVER("crossover"),
    @XmlEnumValue("junction")
    JUNCTION("junction"),
    @XmlEnumValue("blockPost")
    BLOCK_POST("blockPost"),
    @XmlEnumValue("blockSignal")
    BLOCK_SIGNAL("blockSignal");
    private final String value;

    TOcpOperationalType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TOcpOperationalType fromValue(String v) {
        for (TOcpOperationalType c: TOcpOperationalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
