//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOcpPropEquipmentSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOcpPropEquipmentSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="signalBox" type="{http://www.railml.org/schemas/2009}tInterlockingTypes" />
 *       &lt;attribute name="powerstation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hasHomeSignals" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hasStarterSignals" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hasSwitches" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOcpPropEquipmentSummary")
public class TOcpPropEquipmentSummary {

    @XmlAttribute(name = "signalBox")
    protected TInterlockingTypes signalBox;
    @XmlAttribute(name = "powerstation")
    protected Boolean powerstation;
    @XmlAttribute(name = "hasHomeSignals")
    protected Boolean hasHomeSignals;
    @XmlAttribute(name = "hasStarterSignals")
    protected Boolean hasStarterSignals;
    @XmlAttribute(name = "hasSwitches")
    protected Boolean hasSwitches;

    /**
     * Gets the value of the signalBox property.
     * 
     * @return
     *     possible object is
     *     {@link TInterlockingTypes }
     *     
     */
    public TInterlockingTypes getSignalBox() {
        return signalBox;
    }

    /**
     * Sets the value of the signalBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInterlockingTypes }
     *     
     */
    public void setSignalBox(TInterlockingTypes value) {
        this.signalBox = value;
    }

    /**
     * Gets the value of the powerstation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPowerstation() {
        if (powerstation == null) {
            return false;
        } else {
            return powerstation;
        }
    }

    /**
     * Sets the value of the powerstation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPowerstation(Boolean value) {
        this.powerstation = value;
    }

    /**
     * Gets the value of the hasHomeSignals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHasHomeSignals() {
        if (hasHomeSignals == null) {
            return false;
        } else {
            return hasHomeSignals;
        }
    }

    /**
     * Sets the value of the hasHomeSignals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasHomeSignals(Boolean value) {
        this.hasHomeSignals = value;
    }

    /**
     * Gets the value of the hasStarterSignals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHasStarterSignals() {
        if (hasStarterSignals == null) {
            return false;
        } else {
            return hasStarterSignals;
        }
    }

    /**
     * Sets the value of the hasStarterSignals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasStarterSignals(Boolean value) {
        this.hasStarterSignals = value;
    }

    /**
     * Gets the value of the hasSwitches property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHasSwitches() {
        if (hasSwitches == null) {
            return false;
        } else {
            return hasSwitches;
        }
    }

    /**
     * Sets the value of the hasSwitches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasSwitches(Boolean value) {
        this.hasSwitches = value;
    }

}
