//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tStopDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tStopDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aStopDescription"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tStopDescription")
@XmlSeeAlso({
    EStopDescription.class
})
public class TStopDescription {

    @XmlAttribute(name = "commercial")
    protected Boolean commercial;
    @XmlAttribute(name = "stopOnRequest")
    protected Boolean stopOnRequest;
    @XmlAttribute(name = "onOff")
    protected String onOff;
    @XmlAttribute(name = "purpose")
    protected String purpose;
    @XmlAttribute(name = "operatingPeriodRef")
    @XmlIDREF
    protected Object operatingPeriodRef;

    /**
     * Gets the value of the commercial property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCommercial() {
        return commercial;
    }

    /**
     * Sets the value of the commercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommercial(Boolean value) {
        this.commercial = value;
    }

    /**
     * Gets the value of the stopOnRequest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStopOnRequest() {
        return stopOnRequest;
    }

    /**
     * Sets the value of the stopOnRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStopOnRequest(Boolean value) {
        this.stopOnRequest = value;
    }

    /**
     * Gets the value of the onOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnOff() {
        return onOff;
    }

    /**
     * Sets the value of the onOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnOff(String value) {
        this.onOff = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the operatingPeriodRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOperatingPeriodRef() {
        return operatingPeriodRef;
    }

    /**
     * Sets the value of the operatingPeriodRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOperatingPeriodRef(Object value) {
        this.operatingPeriodRef = value;
    }

}
