//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tSwitch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSwitch">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tCommonSwitchAndCrossingData">
 *       &lt;attribute name="type" type="{http://www.railml.org/schemas/2009}tSwitchType" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSwitch")
@XmlSeeAlso({
    ESwitch.class
})
public class TSwitch
    extends TCommonSwitchAndCrossingData
{

    @XmlAttribute(name = "type")
    protected TSwitchType type;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TSwitchType }
     *     
     */
    public TSwitchType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSwitchType }
     *     
     */
    public void setType(TSwitchType value) {
        this.type = value;
    }

}
