//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTrainEngine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTrainEngine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aTrainEngine"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrainEngine")
public class TTrainEngine {

    @XmlAttribute(name = "trainMeanAcceleration")
    protected BigDecimal trainMeanAcceleration;
    @XmlAttribute(name = "trainMaxAcceleration")
    protected BigDecimal trainMaxAcceleration;

    /**
     * Gets the value of the trainMeanAcceleration property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrainMeanAcceleration() {
        return trainMeanAcceleration;
    }

    /**
     * Sets the value of the trainMeanAcceleration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrainMeanAcceleration(BigDecimal value) {
        this.trainMeanAcceleration = value;
    }

    /**
     * Gets the value of the trainMaxAcceleration property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrainMaxAcceleration() {
        return trainMaxAcceleration;
    }

    /**
     * Sets the value of the trainMaxAcceleration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrainMaxAcceleration(BigDecimal value) {
        this.trainMaxAcceleration = value;
    }

}
