//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTrack complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTrack">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.railml.org/schemas/2009}tElementWithIDAndName">
 *       &lt;attribute name="type" type="{http://www.railml.org/schemas/2009}tTrackType" />
 *       &lt;attribute name="mainDir" type="{http://www.railml.org/schemas/2009}tDirValidity" />
 *       &lt;attribute name="infraAttrGroupRef" type="{http://www.railml.org/schemas/2009}tGenericRef" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrack")
@XmlSeeAlso({
    ETrack.class
})
public class TTrack
    extends TElementWithIDAndName
{

    @XmlAttribute(name = "type")
    protected TTrackType type;
    @XmlAttribute(name = "mainDir")
    protected TDirValidity mainDir;
    @XmlAttribute(name = "infraAttrGroupRef")
    @XmlIDREF
    protected Object infraAttrGroupRef;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TTrackType }
     *     
     */
    public TTrackType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTrackType }
     *     
     */
    public void setType(TTrackType value) {
        this.type = value;
    }

    /**
     * Gets the value of the mainDir property.
     * 
     * @return
     *     possible object is
     *     {@link TDirValidity }
     *     
     */
    public TDirValidity getMainDir() {
        return mainDir;
    }

    /**
     * Sets the value of the mainDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDirValidity }
     *     
     */
    public void setMainDir(TDirValidity value) {
        this.mainDir = value;
    }

    /**
     * Gets the value of the infraAttrGroupRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInfraAttrGroupRef() {
        return infraAttrGroupRef;
    }

    /**
     * Sets the value of the infraAttrGroupRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInfraAttrGroupRef(Object value) {
        this.infraAttrGroupRef = value;
    }

}
