//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for tVehicleRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tVehicleRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aVehicleRef"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVehicleRef")
public class TVehicleRef {

    @XmlAttribute(name = "orderNumber", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger orderNumber;
    @XmlAttribute(name = "vehicleRef", required = true)
    @XmlIDREF
    protected Object vehicleRef;
    @XmlAttribute(name = "vehicleCount")
    protected BigInteger vehicleCount;
    @XmlAttribute(name = "frontGangway")
    protected Boolean frontGangway;
    @XmlAttribute(name = "rearGangway")
    protected Boolean rearGangway;

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderNumber(BigInteger value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the vehicleRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVehicleRef() {
        return vehicleRef;
    }

    /**
     * Sets the value of the vehicleRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVehicleRef(Object value) {
        this.vehicleRef = value;
    }

    /**
     * Gets the value of the vehicleCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVehicleCount() {
        return vehicleCount;
    }

    /**
     * Sets the value of the vehicleCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVehicleCount(BigInteger value) {
        this.vehicleCount = value;
    }

    /**
     * Gets the value of the frontGangway property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFrontGangway() {
        return frontGangway;
    }

    /**
     * Sets the value of the frontGangway property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFrontGangway(Boolean value) {
        this.frontGangway = value;
    }

    /**
     * Gets the value of the rearGangway property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRearGangway() {
        return rearGangway;
    }

    /**
     * Sets the value of the rearGangway property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRearGangway(Boolean value) {
        this.rearGangway = value;
    }

}
