//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.06 at 11:34:29 AM CET 
//


package org.railml.schemas._2009;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * 
 * 				technical data of transformer winding
 * 			
 * 
 * <p>Java class for tWinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tWinding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.railml.org/schemas/2009}aWinding"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tWinding")
public class TWinding {

    @XmlAttribute(name = "assemblyName", required = true)
    protected String assemblyName;
    @XmlAttribute(name = "nominalVoltage")
    protected BigDecimal nominalVoltage;
    @XmlAttribute(name = "nominalCurrent")
    protected BigDecimal nominalCurrent;
    @XmlAttribute(name = "transformationRatio")
    protected BigDecimal transformationRatio;
    @XmlAttribute(name = "primaryResistance")
    protected BigDecimal primaryResistance;
    @XmlAttribute(name = "secondaryResistance")
    protected BigDecimal secondaryResistance;
    @XmlAttribute(name = "primaryLeakageInductance")
    protected BigDecimal primaryLeakageInductance;
    @XmlAttribute(name = "secondaryLeakageInductance")
    protected BigDecimal secondaryLeakageInductance;

    /**
     * Gets the value of the assemblyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssemblyName() {
        return assemblyName;
    }

    /**
     * Sets the value of the assemblyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssemblyName(String value) {
        this.assemblyName = value;
    }

    /**
     * Gets the value of the nominalVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNominalVoltage() {
        return nominalVoltage;
    }

    /**
     * Sets the value of the nominalVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNominalVoltage(BigDecimal value) {
        this.nominalVoltage = value;
    }

    /**
     * Gets the value of the nominalCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNominalCurrent() {
        return nominalCurrent;
    }

    /**
     * Sets the value of the nominalCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNominalCurrent(BigDecimal value) {
        this.nominalCurrent = value;
    }

    /**
     * Gets the value of the transformationRatio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTransformationRatio() {
        return transformationRatio;
    }

    /**
     * Sets the value of the transformationRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTransformationRatio(BigDecimal value) {
        this.transformationRatio = value;
    }

    /**
     * Gets the value of the primaryResistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrimaryResistance() {
        return primaryResistance;
    }

    /**
     * Sets the value of the primaryResistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrimaryResistance(BigDecimal value) {
        this.primaryResistance = value;
    }

    /**
     * Gets the value of the secondaryResistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSecondaryResistance() {
        return secondaryResistance;
    }

    /**
     * Sets the value of the secondaryResistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSecondaryResistance(BigDecimal value) {
        this.secondaryResistance = value;
    }

    /**
     * Gets the value of the primaryLeakageInductance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrimaryLeakageInductance() {
        return primaryLeakageInductance;
    }

    /**
     * Sets the value of the primaryLeakageInductance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrimaryLeakageInductance(BigDecimal value) {
        this.primaryLeakageInductance = value;
    }

    /**
     * Gets the value of the secondaryLeakageInductance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSecondaryLeakageInductance() {
        return secondaryLeakageInductance;
    }

    /**
     * Sets the value of the secondaryLeakageInductance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSecondaryLeakageInductance(BigDecimal value) {
        this.secondaryLeakageInductance = value;
    }

}
