= Protokoll Gruppe 03

[cols="<h,<a"]
|===
|Treffen am 27.10.2015    |13:00 Uhr, APB
|Schriftführer            |Robert Mörseburg
|Nächstes Treffen         |03.11.2015 13:00 Uhr APB Foyer +
(Internes Treffen Fr 30.10.15 13:00 Uhr APB Foyer)
|Teilnehmer               |
* Eric Schölzel (Scrum-Master)
* Jonas Schenke
* Oliver Schmidt
* Robert Mörseburg
* Zdravko Yanakiev
* Ronny Kaiser (Betreuer Lehrstuhl SWT)
* Walerian Nesterenko (30 min, Mitarbeiter EBL)
|===

== Bemerkungen
Im letzten Protokoll wurden bereits die eigenen Prototypen als Ziel für den letzten Sprint erwähnt, diese sollen aber erst im aktuellen Sprint fertiggestellt werden. Der neue Abgabetermin ist damit Montag, der 02.11.15.

_Insgesamt gilt_: Fällige Artefakte und Dokumente müssen am Tag vor dem nächsten Treffen bis 16:00 Uhr im `master`-Branch vorliegen.

== Retrospektive des letzten Sprints

Im letzten Sprint wurde der GUI-Prototyp entworfen sowie erste Arbeitsentwürfe für Pflichtenheft und UML-Diagramme erstellt.

Das Lastenheft liegt mittlerweile als Entwurf vor. Die Spezifikation der Telegramme erfolgt bis spätestens Mitte November.

// See http://asciidoctor.org/docs/user-manual/=tables
[options="header"]
|===
|Issue |Aufgabe |Status |Bemerkung
|3	|CRC-Kartenmethode 	|in Bearbeitung 	|während des heutigen Treffens bearbeitet, Ergebnisse folgen
|4	|Pflichtenheft		|in Bearbeitung		|wird im aktuellen Sprint fertig gestellt
|6	|GUI-Prototyp		|fertig 			|bedarf Abnahme durch den Kunden
|7	|Kontextdiagramm	|in Bearbeitung		|Entuwrf bereits im repo
|8	|Anwendungsfalldiagramm	|in Bearbeitung	|bereits komplett, nur noch Übertragung in MagicDraw
|9	|Klassendiagramm	|in Bearbeitung		|Entwruf beim heutigen Treffen erstellt
|10	|Sequenzdiagramm	|offen				|--
|11	|Salespoint aus dem Projekt entfernen	|offen	|niedrige Priorität, erst nach der Analyse
|12	|Java-Version		|in Bearbeitung		| 7 oder 8, nach technischer Spezifikation des Kunden
|13	|Top-Level-Architektur	|in Bearbeitung	|als Komponentendiagramm
|14	|Erster Prototyp 	|in Bearbeitung		|restlihce Prototypen bis Montag abzugeben
|===

== Aktueller Stand

=== Angesprochene Punkte
* _Java Version_ +
  7 oder 8 nach technischer Machbarkeit beim Kunden
* _Warum keine Datenbank_ +
  keine dauehafte Speicherung der Fahrplandaten, in-memory DB ist in Ordnung
* _RailML: Train parts, OCPSTP, Zeiten_ +
  keine Kenntnis des Kunden, aus Spezifikation und gegebener Beispieldatei schließen
* _operating periods_ +
  keine Unterscheidung von Wochen-, Feiertagen, o.ä.
* _INI-Format_ +
  "einfache textbasierte Konfiguration mittels Schlüssel-Wert-Paaren", keine Festlegung auf INI-Format, Dokumentation
* _Projektseite mit Neuigkeiten pflegen_ +
  GitHub-Issues etc. sind ausreichend
* _Funktionsumfang Prototyp_ +
  ähnlich Gästebuch
* _Güterzüge im "Fahrgast"informationssystem_ +
  als zusätzlich einschaltbares Feature

=== Objektorientierte Analyse mittels CRC-Karten

==== Klassenkandidaten
* Halt
* Betriebsstelle / Bahnhof
* Zug
* Zuglauf
* Fahrplan
* Telegramm
* Zeit
* Verbindungsstatus
* Änderung
* Suchabnrage / Ankunfts-/Abfahrts-/Zuglauftafel

==== Zusammenwirken der Klassen
* Unterschiedliche Telegrammtypen mittels Vererbung:
	** Anmeldetelegramm
	** Bestätigungstelegramm
	** Statusdiagramm
	** Zuglauftelegeramm
	** Änderungstelegramm
* Unterschiedliche Anfragetypen mittels Vererbung
	** Abfahrtsanfrage
	** Ankunftsanfrage
	** Zuglaufanfrage
* Biderektionale Assoziation zwischen Bahnhof und dortigen Halten
* Zuglauf (mit Zugnummer, Gattung, ...) besteht aus mehreren Halten, wobei jeder Halt einem Zuglauf zugeordnet ist
* Halt mit:
	** Zuglauf
	** Bahnhof
	** AnkunftSoll
	** AnkunftIst
	** AbfahrtSoll
	** AbfahrtIst
	** GleisSoll
	** GleisIst

=== Offene Fragen an den Kunden
* Sind "Zug" und "Zuglauf" synonym zu verwenden? Insbesondere keine Unterscheidung der physischen Fahrzeuge, sondern der einzelnen Fahrten (eindeutig bestimmt durch Route und Uhrzeiten) im Fahrplan.
* Wie sollen die Fahrten auf der Ankunfts- / Abfahrtstafel sortiert sein? (Sollzeit oder Istzeit)
* An welcher Stelle soll ein Zug mit Verspätung erscheinen? Zur Sollzeit, auch wenn er große Verspätung hat, oder zur Istzeit, dafür bei großer Verspätung eventuell außerhalb des Zeitrahmens der Anzeige. Was passiert, wenn die Sollzeit vorüber ist?
* Wird die Zuggattung der Zugnummer entnommen? Bezieht sie sich also auf einen Zuglauf im obigen Sinne oder auf das physische Fahrzeug?

== Planung des nächsten Sprints

* Defenitive Fertigstellung der eigenen Prototypen
* Pflichtenheft mit Diagrammen und Akzeptanztestfällen (soweit möglich und mit Kundem abgesprochen) fertigstellen
* GUI-Prototyp zur Abnahme durch Kunden als HTML-Seite mit Bildern, dann eventuell Anpassungen
* Fertigstellung der Analysediagramme

Issues siehe oben.
