= Protokoll Gruppe 03

[cols="<h,<a"]
|===
|Treffen am 08.01.2016    |13:00 Uhr, EBL
|Schriftführer            |Oliver Schmidt, Ergänzungen Robert Mörseburg
|Nächstes Treffen         |12.01.2016, 13:00 Uhr, EBL
|Teilnehmer               |
* Eric Schölzel (Scrum-Master)
* Jonas Schenke
* Oliver Schmidt
* Robert Mörseburg (ab 14:30 Uhr)
* Zdravko Yanakiev
* Walerian Nesterenko (Betreuer EBL)
* Ronny Kaiser (Betreuer Lehrstuhl SWT)
|===

== Bemerkungen

Am 05.01.2016 fand ein internes Treffen der Gruppenmitglieder statt. Es wurde der aktuelle Stand besprochen und die Aufgaben bis zum offiziellen Treffen am 08.01.2016 besprochen.

== Retrospektive des letzten Sprints

Im letzten Sprint wurde der spezielle Kundenwunsch nach einer Karte des Liniennetzes bearbeitet. Allerdings konnten dazu bisher nur fiktive Testdaten herangezogen werden, weil eine Spezifikation der Koordinaten innerhalb der RailML-Datei nicht vorliegt.

Außerdem wurde die aktuellste Version der Telegrammspezifikation und deren Erweiterungen implementiert.

Desweiteren wurde der Tesplan teilweise aktualisiert, die Arbeit am Benutzerhandbuch begonnen und weitere Klassen mit Javadoc und Testfällen ausgestattet.

[options="header"]
|===
|Issue |Aufgabe |Status |Bemerkung
|35 |Opera 12 Kompatibilität	|abgeschlossen		|--
|39 |Javadoc 					|abgeschlossen		|--
|48 |Verarbeitung Update-Telegramme |abgeschlossen	|--
|57	|Telegramme parsen 			|abgeschlossen		|--
|65	|Testplan					|in Bearbeitung		|erweitert
|66	|Umschaltung TCP / XML 		|in Bearbeitung		|ebenfalls eventbasiert
|68	|Integration Tests 			|offen 				|--
|69	|Karte des Streckennetzes	|in Bearbeitung		|noch keine realen Testdaten
|===

== Aktueller Stand

=== Treffen am 05.01.2016
Die Umschaltung zwischen Telegrammen und XML durch das Auslösen von Offline-Events funktioniert.
Einige Timeouts müssen aber noch angepasst werden bzw. können ganz entfallen.

Die Liniennetz-Karte funktioniert mit eigenen Testdaten, aber nicht bei Verwendung der XML-Datei, da die Position der Koordinaten darin nicht spezifiziert ist.

Folgende Aufgaben wurden verteilt:

* UML aktualisieren (Jonas)
* Entwicklerdokumentation aktualisieren (Jonas)
* Testplan erweitern (Zdravko)
* Benutzerhandbuch schreiben (Eric)
* Integration Tests (soweit möglich) entwerfen (Olli)
* Telegrammkonstanten in eigene Klasse auslagern (Robert)
* fehlende GUI-Features implementieren (Robert)

In einer Mail wurden einige offfene Punkte mit dem Kunden geklärt:

* Koordinaten liegen wahrscheinlich unter `<infrastructure><operationControlPoints><ocp><geoCoord>` in der RailML-Datei. Weitere Informationenn und eine Besipsieldatei folgen, bis dahin sollen nur Daten vom Telegrammmserver verarbeitet werden.
* Es gibt eine Beispieldatei mit Meldungen, am 08.01.2016 dann auch eine ausführliche.
* Der Fahrplanserver hat bisher nicht entsprechend der Spezifikation gesendet (Dispo-Byte fehlte in den Zugläufen), dies wird bis zum 08.01.2016 behoben.

=== Treffen am 08.01.2016
Abgabe ist am 15.01.2016, Projekt muss wirklich __fertig__ sein.

Der Testplan ist eher abstrakt zu halten. Es wird keinen Testserver für Integration Tests geben, deshalb sind manche nicht realisierbar.

Es gibt keine neue RailML-Datei. Koordinaten sollen nur per Telegramm empfangen werden.

Es traten einige Probleme mit dem korrekten Auslösen der Events zum Umschalten zwischen Telegrammen und XML auf.

Telegramme werden vollständig und korrekt geparst.

Manche Zeiten referenzieren eine Uhrzeit am nächsten Tag, diese haben einen 10tel-Minuten-Wert größer als 20000.

Die Darstellung der Karte wirkte mit den realen Daten etwas verzerrt. Viele Bahnhöfe haben die Koordinaten (0, 0), diese sollen aber laut Kunden genau so dargestellt werden bis sie korrekte Koordinaten erhalten.

== Planung des nächsten Sprints

Im nächsten Sprint wird die Größe und Skalierung der Karte angepasst. Außerdem wird die Arbeit am Benutzerhandbuch fortgesetzt, die grafische Oberfläche wird um die Perlenschnur ergänzt.

Jedes Teammitglied muss desweiteren eine persönliche Evaluation anfertigen.

[options="header"]
|===
|Issue |Aufgabe |Status |Bemerkung
|65	|Testplan					|in Bearbeitung		|aktualisieren, erweitern, neue Tests (durch *alle*)
|66	|Umschaltung TCP / XML 		|in Bearbeitung		|Fehler beheben
|68	|Integration Tests 			|offen 				|soweit möglich
|69	|Karte des Streckennetzes	|fast abgeschlossen	|Größe, Skalierung (durch *Eric*)
|75 |GUI-Elemente				|in Bearbeitung		|Perlenschnur, Aktualisierung, Zeit (durch *Robert*)
|77	|Evaluation					|offen 				|persönlich, siehe Template (durch *alle*)
|78 |Sauberer Shutdown			|offen 				|--
|82	|UML aktualisieren 			|in Bearbeitung 	|(durch *Jonas*)
|===
