= Protokoll Gruppe 03

[cols="<h,<a"]
|===
|Treffen am 12.01.2016    |13:00 Uhr, EBL
|Schriftführer            |Robert Mörseburg
|Nächstes Treffen         |19.01.2016, 13:00 Uhr, APB
|Teilnehmer               |
* Eric Schölzel (Scrum-Master)
* Jonas Schenke
* Oliver Schmidt
* Robert Mörseburg
* Zdravko Yanakiev
* Walerian Nesterenko (Betreuer EBL)
* Ronny Kaiser (Betreuer Lehrstuhl SWT)
|===

== Bemerkungen

Am 15.01.2016 ist Abgabe. An diesem Tag findet deshalb ein weiteres internes Treffen für die abschließenden Tests und eine evenetuelle Übergabe statt.

== Retrospektive des letzten Sprints

Im letzten Sprint wurden die noch bestehenden Probleme mit den Telegrammen, insbesondere dem korrekten Auslösen der Events zum Umschalten zwischen Telegrammverarbeitung und XML-Parsen behoben.

Außerdem wurde an UML-Diagramm, Testplan, Entwicklerdokumentation und Benutzerhandbuch gearbeitet.

[options="header"]
|===
|Issue |Aufgabe |Status |Bemerkung
|65	|Testplan					|in Bearbeitung		|--
|66	|Umschaltung TCP / XML 		|abgeschlossen		|--
|68	|Integration Tests 			|verworfen			|nicht realisierbar
|69	|Karte des Streckennetzes	|fast abgeschlossen	|Anzeige immernoch verzerrt
|75 |GUI-Elemente				|in Bearbeitung		|Zeitanzeige und Verspätungen verbessert
|77	|Evaluation					|offen 				|--
|78 |Sauberer Shutdown			|abgeschlossen		|Server geht beim Beenden zunächst offline
|82	|UML aktualisieren 			|fast abgeschlossen	|letzte Aktualisierungen
|===

== Aktueller Stand

Zum Treffen fand erneut ein Test des Programmes im Eisenbahnlabor statt. Dabei sind folgende Punkte aufgefallen:

* Die Client-ID muss 42 sein, damit konstant Telegramme gesendet werden.
* Der Pfad zur CSV-Datei mit den Meldungstexten soll ebenfalls konfigurierbar sein.
* Cleanup-Events werden jetzt zum richtigen Zeitpunkt ausgelöst.
* Fehlt ein Meldungstext zur angegebenen ID soll ein leerer Sttring angezeigt werden.
* Im TrainRouteTelegram treten viele Stops mit `PASS` auf, diese werden jetzt vom Programm ignoriert.

Die CSV-Datei mit den Meldungstexten liegt momentan unter `\\VELF01\Labor\Fahrplan`. Läuft das Programm wie spezifiziert auf einem SLES11-Server, so muss diese Netzwerkressource im Vorfeld gemounted werden, damit Java daruaf über einen lokalen Pfad zugreifen kann.

Die genauen Abgabemodalitäten werden noch vom Lehrstuhl bekannt gegeben.

== Planung des nächsten Sprints

Bis zum Abgabetermin müssen die fehlenden GUI-Komponenten, insbesondere die Perlenschnur hiinzugefügt werden. Die Darstellung der Karte sollte verbessert weden.

Das Exception-Handling der CSV-Klasse muss geringfügig überarbeitet werden, damit das Programm auch bei fehlender Datei oder falschem Pfad weiterläuft. Außerdem wird ein Semikolon als Trennzeichen verwendet.

Jedes Teammitglied muss desweiteren eine persönliche Evaluation anfertigen.

[options="header"]
|===
|Issue |Aufgabe |Status |Bemerkung
|65	|Testplan					|in Bearbeitung		|fertig stellen (durch *Zdravko*, *Olli*)
|69	|Karte des Streckennetzes	|fast abgeschlossen	|Größe (durch *Eric*, *Robert*)
|70 |Benutzerhandbuch			|in Bearbeitung		|fertig stellen (durch *Eric*)
|75 |GUI-Elemente				|in Bearbeitung		|Perlenschnur (durch *Robert*)
|77	|Evaluation					|offen 				|persönlich, siehe Template (durch *alle*)
|82	|UML aktualisieren 			|fast abgeschlossen	|letzte Aktualisierungen
|===
