= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2015/16

**Von: Eric Schölzel**

**Gruppe: 3**

== Was habe ich gelernt?
Ich habe gelernt, dass eine gute Kommunikation und Arbeitsaufteilung, sowie realistische (aber auch bindende) "Wochenziele" essentiell für das Vorankommen in der Gruppe sind. 
Zudem war es interessant, ein doch schon etwas größeres Projekt Schritt für Schritt zu entwickeln, d.h. Analyse, Entwurf etc. und nicht "einfach drauf loszuprogrammieren". 
Neben der Einarbeitung in das Spring Framework (bzw. Teile davon) habe ich vor allem gelernt, eine Datenstruktur möglichst unabhängig von der Datenquelle zu entwickeln, was nötig war, damit diese sowohl für den Offline-Fahrplan, als auch für die Telegramme zuverlässig funktioniert.
Dabei hat sich gezeigt, wie wichtig (und praktisch) Tests (hier mit JUnit) für solche Bereiche sind - in einer GUI sieht man, falls etwas kaputt ist, einen groben Schnitzer in der Datenstruktur wäre ohne Tests jedoch sehr schwierig auszumachen und wird im Zweifelsfall erst dann bemerkt, wenn es zu spät ist. Es hat sich aber auch gezeigt, dass das Testen in manchen Bereichen sehr schwierig sein kann (GUI, TCP/IP, Webteil, ...) und deshalb mit solchen Methoden nicht unbedingt das Mittel der Wahl ist.
Regelmäßige Testläufe in der "echten" Umgebung (d.h. im Eisenbahnbetriebslabor) sind nicht nur deshalb unbedingt notwendig, da sich manche Dinge dann doch anders verhalten können als geplant.

= Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
Ich kann behaupten, dass wir mit unserer Teamzusammenstellung eine Menge Glück hatten. Wir hatten ein sehr gutes Team, dass sich wunderbar ergänzt hat, bei keinem hatte man das Gefühl, dass er einfach andere die Arbeit machen lässt und sich selbst zurücklehnt. Bestätigt hat sich, dass eine gute Kommunikation von Anfang an sehr wichtig ist.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks gemacht?
Vor allem eines: Einarbeitung in ein solches Framework braucht vor allem Zeit. Selbst nach all den Wochen haben wir nur einen Teil des Spring-Frameworks kennengelernt. Die Einarbeitungszeit in ein solches Framework lohnt sich jedoch, all dies selbst zu entwickeln wäre blanker Wahnsinn. Für ein kleines 2-Tages-Projekt wäre ein solches Framework natürlich vollkommen übertrieben, sofern man damit noch keine Erfahrungen hat.

Teilweise hat man als Anfänger jedoch Probleme, die Vorgänge nachzuvollziehen. So hatte man z.B. das Gefühl, dass nirgendwo erklärt wurde, was denn genau ein "Bean" ist, der Begriff wurde einem jedoch "überall um die Ohren gehauen". Demzufolge hat sich dann (nicht nur in unserer Gruppe) der Spitzname "Spring Magic" für solche Dinge ergeben, die das Framework zwar irgendwie macht, man aber keine wirkliche Ahnung hat, wie denn nun genau das ganze funktioniert ;)


== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
Ich denke, dass es wichtig ist, dass der Kunde zeitnah Rückmeldungen gibt. Obwohl sich unser Kunde manchmal etwas viel Zeit gelassen hat (und diverse Spezifikationen nicht immer ganz mit der Wirklichkeit übereinstimmten und es deshalb teilweise unnötige Rumtestereien gab), lief die Kommunikation bei uns dennoch relativ gut. Das lag auch daran, dass der Kunde fast bei allen Treffen anwesend war und für Rückfragen zur Verfügung stand, was wohl nicht selbstverständlich ist (wenn man von anderen Gruppen hört, bei denen der Kunde fast nie da war...)

== Sonstiges und Anmerkungen
-
