= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2015/16

**Von: Zdravko Yanakiev**

**Gruppe: 3**

== Was habe ich gelernt?
Ich habe gelernt, die verschiedenen Komponenten des Spring-Frameworks zu verwenden, insb. Spring MVC und OXM. Ich habe Erfahrung mit JUnit 4 und Javadoc gemacht. Ich habe gelernt, wie eine vollständige Softwareentwicklung abläuft (Analyse, Entwurf, Implementierung). Ich habe auch meine Kenntnisse in der UML-Modellierung mit MagicDraw verbessert. Ich habe das Konzept vom Domain Driven Design kennengelernt.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
Eine klare Aufgabenteilung ist sehr wichtig, damit kein Teammitglied überfordert bzw. unterfordert ist. Die Teammitglieder müssen sich früh im Praktikum für eine geeignete Kommunikationsweise (IM, E-Mail usw.) entscheiden.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks gemacht?
Man braucht viel Zeit, um sich in ein Framework einzuarbeiten, da es verschiedene für den Entwickler neue Konzepte verwendet. Danach ist es aber gut dafür geeignet, eine vollständige Anwendung schnell zu implementieren. Bibliotheken erleichtern die alltäglichen Aufgaben des Programmierers.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
* Kleinere Gruppen

== Sonstiges und Anmerkungen
Die Kommunikation mit dem Kunden und seine rechtzeitige Reaktion auf Fragen des Teams sind von großer Bedeutung.
