= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2015/16

**Von:** Oliver Schmidt

**Gruppe: 3**

== Was habe ich gelernt?
* Entwicklungszyklus eines Softwareprojekts von der Konzipierung über Entwurf, Design, Implementierung bis zum Release
* Arbeit mit einem inversion of control Framework
* Multithreading
* Netzwerkkommunikation über Sockets
* Kommunikation mit dem Kunden, gemeinsame Erarbeitung des Programms, Präsentation der Ergebnisse (sich gut verkaufen)
* schreiben sinnvoller Tests mit JUnit
* Erstellen von Mockobjekten und Funktionsstubs

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
* Engagement der einzelnen Teammitglieder ist wichtig, war bei uns aber gut
* Arbeitsteilung ist erforderlich un funktioniert gut, ein gewisser grober Überblick sollte allerdings bei allen vorhanden sein
* insgesamt bin ich mit unser Zusammenarbeit in der Gruppe zufrieden
* Zeitplanung pro Woche sollte Platz für unvorhergesehene Komplikationen lassen


== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks gemacht?
* Einarbeitung in Frameworks erfordert sehr viel Lesezeit
* meistens kann man bestehende Lösungen weiterverwenden, manchmal lohnt sich auch die Entwicklung einer eigenen Lösung
* inversion of control kann die Kopplung der Komponenten vereinfachen, ist aber insbesondere am Anfang schwer zu verstehen

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
* continuous integration nicht nur im master branch, da dieser ja möglichst immer stabil sein sollte
* Förderung eines sinvollen GIT workflows (Arbeit in develop, nur stabiler code in master, etc.
* Verwendung von freier Software z. B. für UML Modellierung

== Sonstiges und Anmerkungen
* obwohl die Kommunikation mit dem Kunden insgesamt gut gelaufen ist, hat das Fehlen von Spezifikationen über lange Zeit (und die mangelnde Korrektheit der gelieferten) den Projektverlauf teilweise verzögert. Empfehlungen, wie damit umzugehen ist
* leider waren sinnvolle Integration tests durch das Fehlen eines Testservers nicht möglich, das Testen vor Ort war ein zusätzlicher Aufwand (aber in Ordnung)
